---
title: "Lifetime_Sim_Collective_Narrow"
author: "Piper Zimmerman"
date: "May 7, 2024"
output: html_document
---

```{r load.narrow.exp}
load("individual_exp_narrow.RData")
load("mean_exp_narrow.RData")
load("inverse_exp_narrow.RData")
load("mean_inverse_exp_narrow.RData")
load("inverse_mean_exp_narrow.RData")
```

```{r load.narrow.wb}
load("mean_wb_narrow.RData")
load("individual_wb_narrow.RData")
load("inverse_wb_narrow.RData")
load("mean_inverse_wb_narrow.RData")
load("inverse_mean_wb_narrow.RData")
load("individual_wb_wb_narrow.RData")
```



```{r plot.a.narrow}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Trunc Norm Model", "Individual Exp Data, Exp Model")
N_df.a <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Median = c(exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2]))))), 
  upper = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))[2])), 
  lower = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))[1]))
)
N_df.a$x <- factor(N_df.a$x, levels = desired_order)

N_a.plot <- ggplot(N_df.a, aes(x, Median)) +
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.a, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip()
N_a.plot
ggsave("n.a.comp.exp.png", plot = N_a.plot, width = 8, height = 5)
```

```{r plot.Topt.narrow}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Trunc Norm Model", "Individual Exp Data, Exp Model")
N_df.b <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Median = c(median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2])))), 
  upper = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2])))[2]), 
  lower = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2])))[1])
)
N_df.b$x <- factor(N_df.b$x, levels = desired_order)

N_b.plot <- ggplot(N_df.b, aes(x, Median)) +
  geom_point(col = cividis(3)[1]) +
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip()
N_b.plot
ggsave("n.Topt.comp.exp.png", plot = N_b.plot, width = 8, height = 5)
```

```{r plot.c.narrow}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Trunc Norm Model", "Individual Exp Data, Exp Model")
N_df.c <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Median = c((median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2]))))), 
  upper = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))[2])), 
  lower = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))[1]))
)
N_df.c$x <- factor(N_df.c$x, levels = desired_order)

N_c.plot <- ggplot(N_df.c, aes(x, Median)) +
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.c, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip()
N_c.plot
ggsave("n.c.comp.exp.png", plot = N_c.plot, width = 8, height = 5)
```

```{r plot.a.narrow.log}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")
log_N_df.a <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Mean = c(exp(mean(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1])))[1]))
)
log_N_df.a$x <- factor(log_N_df.a$x, levels = desired_order)

log_N_a.plot <- ggplot(log_N_df.a, aes(x, log(Mean))) +
  geom_point(col = cividis(3)[1]) +
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) +
  labs(title = "A", x = "Method") +
  geom_hline(yintercept = log(true.a), linetype = "dashed", color = cividis(3)[3]) +
  theme_classic() +
  coord_flip()
log_N_a.plot
```

```{r plot.Topt.narrow.log}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")
log_N_df.b <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Mean = c(mean(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1])))[1])
)
log_N_df.b$x <- factor(log_N_df.b$x, levels = desired_order)

log_N_b.plot <- ggplot(log_N_df.b, aes(x, log(Mean))) +
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) + 
  labs(title = "B", x = "Method") +
  geom_hline(yintercept = log(true.Topt), linetype = "dashed", color = cividis(3)[3])+
  theme_classic() + 
  coord_flip()
log_N_b.plot
```

```{r plot.c.narrow.log}
desired_order <- c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                      "Individual Inverse Exp Data, Trunc Norm Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")
log_N_df.c <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Mean = c((mean(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1])))[1]))
)
log_N_df.c$x <- factor(log_N_df.c$x, levels = desired_order)

log_N_c.plot <- ggplot(log_N_df.c, aes(x, log(Mean))) +
  geom_point(col = cividis(3)[1]) +
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) +
  labs(title = "C", x = "Method") +
  geom_hline(yintercept = log(true.c), linetype = "dashed", color = cividis(3)[3]) +
  theme_classic() +
  coord_flip()
log_N_c.plot
```



```{r plot.a.narrow.wb}
desired_order.wb <- c("Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Trunc Norm Model", "Individual WB Data, Exp Model", "Individual WB Data, WB Model")

df.a.wb.n <- data.frame(
  x = factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model")), 
  Median = c(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))),
             exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))), 
           exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2]))))), 
  upper = c(exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))[2]),
            exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))[2])), 
  lower = c(exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))[1]),
            exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))[1]))
)
df.a.wb.n$x <- factor(df.a.wb.n$x, levels = desired_order.wb)
a.wb.plot.n <- ggplot(df.a.wb.n, aes(x, Median)) +
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.a, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip() + 
  ylim(0, 0.0025)
a.wb.plot.n
ggsave("n.a.comp.wb.png", plot = a.wb.plot.n, width = 8, height = 5)
```

```{r plot.Topt.narrow.wb}
desired_order.wb <- c("Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Trunc Norm Model", "Individual WB Data, Exp Model", "Individual WB Data, WB Model")

df.b.wb.n <- data.frame(
  x = factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model")), 
  Median = c(median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2]))),
             median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2]))), 
           median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))), 
  upper = c(hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))[2],
            hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))[2]), 
  lower = c(hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))[1],
            hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))[1])
)
df.b.wb.n$x <- factor(df.b.wb.n$x, levels = desired_order.wb)
b.wb.plot.n <- ggplot(df.b.wb.n, aes(x, Median)) +
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip()
b.wb.plot.n
ggsave("n.Topt.comp.wb.png", plot = b.wb.plot.n, width = 8, height = 5)
```

```{r plot.c.narrow.wb}
desired_order.wb <- c("Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Trunc Norm Model", "Individual WB Data, Exp Model", "Individual WB Data, WB Model")
df.c.wb.n <- data.frame(
  x = factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model")), 
  Median = c((median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2])))),
             (median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
           (median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2]))))), 
  upper = c((hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2])))[2]),
            (hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))[2])), 
  lower = c((hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2])))[1]),
            (hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))[1]))
)
df.c.wb.n$x <- factor(df.c.wb.n$x, levels = desired_order.wb)
c.wb.plot.n <- ggplot(df.c.wb.n, aes(x, Median)) +
  geom_point(col = plasma(3)[1]) +
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) +
  labs(x = "Method") +
  geom_hline(yintercept = true.c, linetype = "dashed", color = "black") +
  theme_classic() +
  coord_flip()
c.wb.plot.n
ggsave("n.c.comp.wb.png", plot = c.wb.plot.n, width = 8, height = 5)
```

```{r plot.a.narrow.wb.log}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.a.wb.log.n <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(exp(mean(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a.wb.log.n$x <- factor(df.a.wb.log.n$x, levels = desired_order.wb)
a.wb.log.plot.n <- ggplot(df.a.wb.log.n, aes(x, log(Mean))) +
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) +
  labs(title = "A", x = "Method") +
  geom_hline(yintercept = log(true.exp.a), linetype = "dashed", color = plasma(3)[3]) +
  theme_classic() +
  coord_flip()
a.wb.log.plot.n
```

```{r plot.Topt.narrow.wb.log}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.b.wb.log.n <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(mean(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1])))[1])
)
df.b.wb.log.n$x <- factor(df.b.wb.log.n$x, levels = desired_order.wb)
b.wb.log.plot.n <- ggplot(df.b.wb.log.n, aes(x, log(Mean))) +
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) +
  labs(title = "Topt", x = "Method") +
  geom_hline(yintercept = log(true.Topt), linetype = "dashed", color = plasma(3)[3]) +
  theme_classic() +
  coord_flip()
b.wb.log.plot.n
```

```{r plot.c.narrow.wb.log}
desired_order.wb.n <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", 
                      "Individual Inverse WB Data, Trunc Norm Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.c.wb.log.n <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c((mean(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c.wb.log.n$x <- factor(df.c.wb.log.n$x, levels = desired_order.wb)
c.wb.log.plot.n <- ggplot(df.c.wb.log.n, aes(x, log(Mean))) +
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) +
  labs(title = "C", x = "Method") +
  geom_hline(yintercept = log(true.exp.c), linetype = "dashed", color = plasma(3)[3]) +
  theme_classic() +
  coord_flip()
c.wb.log.plot.n
```



```{r plot.a.narrow.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.a.compare.n <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(exp(mean(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1]))))), 
  
  upper = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c(exp(hdi(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a.compare.n$x <- factor(df.a.compare.n$x, levels = desired_order.compare)
a.compare.plot.n <- ggplot(df.a.compare.n, aes(x, Mean)) +
  geom_point(col = viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) +
  labs(title = "A", x = "Method") +
  geom_hline(yintercept = true.a, linetype = "dashed", color = viridis(3)[3]) +
  theme_classic() +
  coord_flip()
a.compare.plot.n
```

```{r plot.Topt.narrow.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.b.compare.n <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(mean(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1]))))), 
  
  upper = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c(hdi(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1])))[1]))
)
df.b.compare.n$x <- factor(df.b.compare.n$x, levels = desired_order.compare)
b.compare.plot.n <- ggplot(df.b.compare.n, aes(x, Mean)) +
  geom_point(col = viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) +
  labs(title = "Topt", x = "Method") +
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = viridis(3)[3]) +
  theme_classic() +
  coord_flip()
b.compare.plot.n
```

```{r plot.c.narrow.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.c.compare.n <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c((mean(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1]))))), 
  
  upper = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c((hdi(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c.compare.n$x <- factor(df.c.compare.n$x, levels = desired_order.compare)
c.compare.plot.n <- ggplot(df.c.compare.n, aes(x, Mean)) +
  geom_point(col = viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) +
  labs(title = "C", x = "Method")+
  geom_hline(yintercept = true.c, linetype = "dashed", color = viridis(3)[3]) +
  theme_classic() +
  coord_flip()
c.compare.plot.n
```



```{r exp.topt.maxlife.mean.narrow}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND EXP DATA EXP MODEL
ind.exp.n <- function(x){
  (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (x -
         median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))
}

# MEAN EXP DATA EXP MODEL
mean.exp.n <- function(x){
  (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (x -
         median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2]))))
}

# INV EXP DATA EXP MODEL
inv.exp.n <- function(x){
  (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (x -
         median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2]))))
}


# MEAN INV EXP DATA EXP MODEL
mean.inv.exp.n <- function(x){
  (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (x -
         median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2]))))
}


# INV MEAN EXP DATA EXP MODEL
inv.mean.exp.n <- function(x){
  (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (x -
         median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2]))))
}

topt.mean.exp.n <- data.frame(
  Topt = c(optimize(ind.exp.n, interval = c(-100, 200))$minimum, 
         optimize(mean.exp.n, interval = c(-100, 200))$minimum, 
         optimize(inv.exp.n, interval = c(-100, 200))$minimum, 
         optimize(mean.inv.exp.n, interval = c(-100, 200))$minimum, 
         optimize(inv.mean.exp.n, interval = c(-100, 200))$minimum, 
         optimize(f, interval = c(-100, 200))$minimum), 
  Lifetime = c(1/optimize(ind.exp.n, interval = c(-100, 200))$objective, 
            1/optimize(mean.exp.n, interval = c(-100, 200))$objective, 
            1/optimize(inv.exp.n, interval = c(-100, 200))$objective, 
            1/optimize(mean.inv.exp.n, interval = c(-100, 200))$objective, 
            1/optimize(inv.mean.exp.n, interval = c(-100, 200))$objective, 
            1/optimize(f, interval = c(-100, 200))$objective
            ), 
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model",  "True Curve"))
)

# Center point coordinates
center_x.exp.n <- topt.mean.exp.n$Topt[6]
center_y.exp.n <- topt.mean.exp.n$Lifetime[6]

# Plotting
ggplot(topt.mean.exp.n, aes(x = Topt, y = Lifetime, color = Method)) +
  geom_point() +
  geom_point(x = center_x.exp.n, y = center_y.exp.n, size = 3, col = viridis(6)[6], shape = 8) +
  labs(title = "Lifetime vs Topt, Narrow Interval (Posterior Mean)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Topt", 
       y = "Lifetime") +
  theme_minimal() +
  scale_color_manual(values = viridis(6)) +
  coord_cartesian(xlim = c(center_x.exp.n - 1, center_x.exp.n + 1), ylim = c(center_y.exp.n - 13, center_y.exp.n + 13))

```

```{r exp.topt.maxlife.boxplot.narrow}
evaluate_expression <- function(x, a, Topt, c) {
  result <- a * (x - Topt)^2 + c
  return(result)
}

df_list.n <- list(df.new1_N, df.new2_N, df.new3_N, df.new4_N, df.new5_N)
min_x_values_list.n <- list()
min_values_list.n <- list()

for (df_index in 1:length(df_list.n)) {
  df <- df_list.n[[df_index]]
  min_x_values.n <- numeric()
  min_values.n <- numeric()
  
  if (df_index  == 1) {
    a_col <- 3
    Topt_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    Topt_col <- 5
    c_col <- 1
  }
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    Topt <- df[i, Topt_col]
    c <- df[i, c_col]
    responses.n <- evaluate_expression(xseq, a, Topt, c)
    min_x.n <- xseq[which.min(responses.n)]
    min_value.n <- min(responses.n)
    min_x_values.n <- c(min_x_values.n, min_x.n)
    min_values.n <- c(min_values.n, min_value.n)
  }
  min_x_values_list.n[[length(min_x_values_list.n) + 1]] <- min_x_values.n
  min_values_list.n[[length(min_values_list.n) + 1]] <- min_values.n
}

double.box.df.n <- data.frame(
  Topt = c(min_x_values_list.n[[1]], 
           min_x_values_list.n[[2]], 
           min_x_values_list.n[[3]], 
           min_x_values_list.n[[4]], 
           min_x_values_list.n[[5]], 
           23.3034735), 
  Lifetime = c(1/min_values_list.n[[1]], 
               1/min_values_list.n[[2]], 
               1/min_values_list.n[[3]], 
               1/min_values_list.n[[4]], 
               1/min_values_list.n[[5]], 
               15.433231), 
  Method = factor(c(rep("Individual Exp Data, Exp Model", 938), rep("Mean Exp Data, Trunc Norm Model", 938), rep("Individual Inverse Exp Data, Trunc Norm Model", 938), 
               rep("Mean Inverse Exp Data, Trunc Norm Model", 938), rep("Inverse Mean Exp Data, Trunc Norm Model", 938), "True Curve")
               )
)

plot.x.n <- ggplot(double.box.df.n, aes(x = Method, y = Topt)) +
  geom_boxplot()
plot.x.n <- layer_data(plot.x.n)[, 1:6]

plot.y.n <- ggplot(double.box.df.n, aes(x = Method, y = Lifetime)) +
  geom_boxplot() 
plot.y.n <- layer_data(plot.y.n)[, 1:6]

dub.n<- double.box.df.n |> group_by(Method) |> summarise(medianTopt = median(Topt), 
                                                     medianLife = median(Lifetime), 
                                                     q1Topt = quantile(Topt, probs = 0.25), 
                                                     q3Topt = quantile(Topt, probs = 0.75), 
                                                     q1Life = quantile(Lifetime, probs = 0.25), 
                                                     q3Life = quantile(Lifetime, probs = 0.75)) |> 
  mutate(iqrTopt = q3Topt-q1Topt, 
         iqrLife = q3Life-q1Life, 
         maxTopt = q3Topt + 1.5 * iqrTopt, 
         minTopt = q1Topt - 1.5 * iqrTopt, 
         maxLife = q3Life + 1.5 * iqrLife, 
         minLife = q1Life - 1.5 * iqrLife, 
         Middle.Topt = plot.x.n$middle, 
         Middle.Life = plot.y.n$middle)

dub.n$Method <- factor(dub.n$Method, levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))
medianTopt.True.n <- as.numeric(rep(dub.n[6, 2], 5))
medianLife.True.n <- as.numeric(rep(dub.n[6, 3], 5))

colnames(plot.x.n) <- paste0("x.", gsub("y", "", colnames(plot.x.n)))
colnames(plot.y.n) <- paste0("y.", gsub("y", "", colnames(plot.y.n)))
df.n <- cbind(plot.x.n, plot.y.n)
df.n$Method <- factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

ggplot(data = dub.n[1:5, ], aes(fill = Method, color = Method)) +
  scale_color_manual(values = viridis(5)) +
  scale_fill_manual(values = viridis(5)) +
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), 
            color = "black", fill = NA) +
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), alpha = 0.3) +
  geom_segment(aes(x = minTopt, y = plot.y.n$y.middle[1:5], xend = maxTopt, yend = plot.y.n$y.middle[1:5])) + #whiskers
  geom_segment(aes(x = minTopt, y = q1Life, xend = minTopt, yend = q3Life)) + #lower end
  geom_segment(aes(x = maxTopt, y = q1Life, xend = maxTopt, yend = q3Life)) + #upper end
  geom_segment(aes(x = plot.x.n$x.middle[1:5], y = minLife, xend = plot.x.n$x.middle[1:5], yend = maxLife)) + #whiskers
  geom_segment(aes(x = q1Topt, y = minLife, xend = q3Topt, yend = minLife)) + #lower end
  geom_segment(aes(x = q1Topt, y = maxLife, xend = q3Topt, yend = maxLife)) + #upper end
  theme_classic() +
  #facet_wrap(dub.n$Method[1:5], nrow = 2, scales = "free") +
  geom_point(aes(x = medianTopt.True.n, y = medianLife.True.n), color = "black", show.legend = FALSE) +
  geom_vline(aes(xintercept = medianTopt.True.n), color = "black", linetype = "dashed") +
  geom_hline(aes(yintercept = medianLife.True.n), color = "black", linetype = "dashed") +
  #theme(legend.position = "none") +
  labs(title = "Boxplot of Optimal Temperature and Maximum Lifetime", 
       x = "Optimal Temperature", 
       y = "Maximum Lifetime")
ggsave("N_Topt_Life_Exp.png", width = 8, height = 5)
```

```{r exp.topt.maxlife.med.narrow}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND EXP DATA EXP MODEL
ind.exp.med.n <- function(x){
  (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 1]))))*(x - 
         median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 1]))))^2 +
         median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 1]))))
}

# MEAN EXP DATA EXP MODEL
mean.exp.med.n <- function(x){
  (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 1]))))*(x -
         median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 1]))))^2 +
         median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 1]))))
}

# INV EXP DATA EXP MODEL
inv.exp.med.n <- function(x){
  (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 1]))))*(x -
         median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 1]))))^2 +
         median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 1]))))
}


# MEAN INV EXP DATA EXP MODEL
mean.inv.exp.med.n <- function(x){
  (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 1]))))*(x -
         median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 1]))))^2 +
         median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 1]))))
}

# INV MEAN EXP DATA EXP MODEL
inv.mean.exp.med.n <- function(x){
  (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 1]))))*(x -
         median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 1]))))^2 +
         median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 1]))))
}


topt.mean.exp.med.n <- data.frame(
  Topt = c(optimize(ind.exp.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.exp.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.exp.med.n, interval = c(-100, 200))$minimum, 
         optimize(mean.inv.exp.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.exp.med.n, interval = c(-100, 200))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.exp.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.exp.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.exp.med.n, interval = c(-100, 200))$objective, 
            1/optimize(mean.inv.exp.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.exp.med.n, interval = c(-100, 200))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))
)

# Center point coordinates
center_x.exp.med.n <- topt.mean.exp.med.n$Topt[6]
center_y.exp.med.n <- topt.mean.exp.med.n$Lifetime[6]

# Plotting
ggplot(topt.mean.exp.med.n, aes(x = Topt, y = Lifetime, color = Method)) +
  geom_point() +
  geom_point(x = center_x.exp.med.n, y = center_y.exp.med.n, size = 3, col = viridis(6)[6], shape = 8) +
  labs(title = "Lifetime vs Topt, Narrow Interval (Posterior Median)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Topt", 
       y = "Lifetime") +
  theme_minimal() +
  scale_color_manual(values = viridis(6)) +
  coord_cartesian(xlim = c(center_x.exp.med.n - 1, center_x.exp.med.n + 1), ylim = c(center_y.exp.med.n - 85, center_y.exp.med.n + 5))

```

```{r WB.topt.maxlife.mean}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}
# IND WB DATA EXP MODEL
ind.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 1])))
}

# MEAN WB DATA EXP MODEL
mean.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 1])))
}

# INV WB DATA EXP MODEL
inv.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 1])))
}


# MEAN INV WB DATA EXP MODEL
mean.inv.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 1])))
}


# INV MEAN WB DATA EXP MODEL
inv.mean.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 1])))
}


# IND WB DATA WB MODEL
ind.wb.wb.n <- function(x){
  exp(mean(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 1]))))*(x -
         mean(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 1]))))^2 +
         mean(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 1])))
}

topt.mean.wb.n<-data.frame(
  Topt = c(optimize(ind.wb.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.wb.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.wb.n, interval = c(-100, 200))$minimum, 
         optimize(mean.inv.wb.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.wb.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(ind.wb.wb.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.wb.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.wb.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.wb.n, interval = c(-100, 200))$objective, 
            1/optimize(mean.inv.wb.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.wb.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(ind.wb.wb.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"), 
               levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))
)

# Center point coordinates
center_x.wb.n <- topt.mean.wb.n$Topt[7]
center_y.wb.n <- topt.mean.wb.n$Lifetime[7]

# Plotting
ggplot(topt.mean.wb.n, aes(x = Topt, y = Lifetime, color = Method)) +
  geom_point() +
  geom_point(x = center_x.wb.n, y = center_y.wb.n, size = 3, col = plasma(7)[7], shape = 8) +
  labs(title = "Lifetime vs Topt, Narrow Interval (Posterior Mean)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Topt", 
       y = "Lifetime") +
  theme_minimal() +
  scale_color_manual(values = plasma(7)) +
  coord_cartesian(xlim = c(center_x.wb.n - 1, center_x.wb.n + 1), ylim = c(center_y.wb.n - 3, center_y.wb.n + 3))
```

```{r WB.topt.maxlife.boxplot}
evaluate_expression <- function(x, a, Topt, c) {
  result <- a * (x - Topt)^2 + c
  return(result)
}

df_list.wb.n <- list(df.new6_W_N, df.new1_W_N, df.new2_W_N, df.new3_W_N, df.new4_W_N, df.new5_W_N)

min_x_values_list.wb.n <- list()
min_values_list.wb.n <- list()

for (df_index.wb.n in 1:length(df_list.wb.n)) {
  df.wb.n <- df_list.wb.n[[df_index.wb.n]]
  min_x_values.wb.n <- numeric()
  min_values.wb.n <- numeric()
  
  if (df_index.wb.n  == 2) {
    a_col <- 3
    Topt_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    Topt_col <- 5
    c_col <- 1
  }
  for (i in 1:nrow(df.wb.n)) {
    a <- exp(df.wb.n[i, a_col])
    Topt <- df.wb.n[i, Topt_col]
    c <- df.wb.n[i, c_col]
    responses.wb.n <- evaluate_expression(xseq, a, Topt, c)
    min_x.wb.n <- xseq[which.min(responses.wb.n)]
    min_value.wb.n <- min(responses.wb.n)
    min_x_values.wb.n <- c(min_x_values.wb.n, min_x.wb.n)
    min_values.wb.n <- c(min_values.wb.n, min_value.wb.n)
  }
  min_x_values_list.wb.n[[length(min_x_values_list.wb.n) + 1]] <- min_x_values.wb.n
  min_values_list.wb.n[[length(min_values_list.wb.n) + 1]] <- min_values.wb.n
}



double.box.df.wb.n <- data.frame(
  Topt = c(min_x_values_list.wb.n[[6]],
           min_x_values_list.wb.n[[1]], 
           min_x_values_list.wb.n[[2]], 
           min_x_values_list.wb.n[[3]], 
           min_x_values_list.wb.n[[4]], 
           min_x_values_list.wb.n[[5]],
           22.3), 
  Lifetime = c(1/min_values_list.wb.n[[6]],
               1/min_values_list.wb.n[[1]], 
               1/min_values_list.wb.n[[2]], 
               1/min_values_list.wb.n[[3]], 
               1/min_values_list.wb.n[[4]], 
               1/min_values_list.wb.n[[5]], 
               15.433231), 
  Method = factor(c(rep("Individual WB Data, WB Model", 938), rep("Individual WB Data, Exp Model", 938), rep("Mean WB Data, Trunc Norm Model", 938), rep("Individual Inverse WB Data, Trunc Norm Model", 938), 
               rep("Mean Inverse WB Data, Trunc Norm Model", 938), rep("Inverse Mean WB Data, Trunc Norm Model", 938), "True Curve"), 
               levels = c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", 
                "True Curve")
               )
)
plot.x.wb.n <- ggplot(double.box.df.wb.n, aes(x = Method, y = Topt))+
  geom_boxplot()
plot.x.wb.n <- layer_data(plot.x.wb.n)[, 1:18]

plot.y.wb.n <- ggplot(double.box.df.wb.n, aes(x = Method, y = Lifetime))+
  geom_boxplot() 
plot.y.wb.n <- layer_data(plot.y.wb.n)[, 1:18]

colnames(plot.x.wb.n) <- paste0("x.", gsub("y", "", colnames(plot.x.wb.n)))
colnames(plot.y.wb.n) <- paste0("y.", gsub("y", "", colnames(plot.y.wb.n)))

df.wb.n <- cbind(plot.x.wb.n, plot.y.wb.n)
df.wb.n$Method <- factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", 
                "True Curve"))


dub.wb.n <- double.box.df.wb.n |> group_by(Method) |> summarise(medianTopt = median(Topt), 
                                                     medianLife = median(Lifetime), 
                                                     q1Topt = quantile(Topt, probs = 0.25), 
                                                     q3Topt = quantile(Topt, probs = 0.75), 
                                                     q1Life = quantile(Lifetime, probs = 0.25), 
                                                     q3Life = quantile(Lifetime, probs = 0.75)) |> 
  mutate(iqrTopt = q3Topt-q1Topt, 
         iqrLife = q3Life-q1Life, 
         maxTopt = q3Topt + 1.5 * iqrTopt, 
         minTopt = q1Topt - 1.5 * iqrTopt, 
         maxLife = q3Life + 1.5 * iqrLife, 
         minLife = q1Life - 1.5 * iqrLife, 
         Middle.Topt = plot.x.wb.n$middle, 
         Middle.Life = plot.y.wb.n$middle)
dub.wb.n$Method <- factor(dub.wb.n$Method, levels = c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", 
                "True Curve"))
medianTopt.True.wb.n <- as.numeric(rep(dub.wb.n[7, 2], 6))
medianLife.True.wb.n <- as.numeric(rep(dub.wb.n[7, 3], 6))

dub.wb.n[4, 13] <- 0
plot.x.wb.n[6,3] <- (plot.x.wb.n[6,2] + plot.x.wb.n[6,4])/2

ggplot(data = dub.wb.n[1:6, ], aes(fill = Method, color = Method)) +
  scale_color_manual(values = plasma(6)) +
  scale_fill_manual(values = plasma(6)) +
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), 
            color = "black", fill = NA) +
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), alpha = 0.3) +
  geom_segment(aes(x = minTopt, y = plot.y.wb.n$y.middle[1:6], xend = maxTopt, yend = plot.y.wb.n$y.middle[1:6])) + #whiskers
  geom_segment(aes(x = minTopt, y = q1Life, xend = minTopt, yend = q3Life)) + #lower end
  geom_segment(aes(x = maxTopt, y = q1Life, xend = maxTopt, yend = q3Life)) + #upper end
  geom_segment(aes(x = plot.x.wb.n$x.middle[1:6], y = minLife, xend = plot.x.wb.n$x.middle[1:6], yend = maxLife)) + #whiskers
  geom_segment(aes(x = q1Topt, y = minLife, xend = q3Topt, yend = minLife)) + #lower end
  geom_segment(aes(x = q1Topt, y = maxLife, xend = q3Topt, yend = maxLife)) + #upper end
  theme_classic() +
  geom_point(aes(x = medianTopt.True.wb.n, y = medianLife.True.wb.n), color = "black", show.legend = FALSE) +
  geom_vline(aes(xintercept = medianTopt.True.wb.n), color = "black", linetype = "dashed") +
  geom_hline(aes(yintercept = medianLife.True.wb.n), color = "black", linetype = "dashed") +
  #facet_wrap(dub.wb.n$Method[1:6], nrow = 2, scales = "free") +
  #theme(legend.position = "none") +
  labs(title = "Boxplot of Optimal Temperature and Maximum Lifetime", 
       x = "Optimal Temperature", 
       y = "Maxium Lifetime") +
  coord_cartesian(xlim = c(17, 23), ylim = c(5,20))
ggsave("N_Topt_Life_WB.png", width = 8, height = 5)
```

```{r WB.topt.maxlife.med}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}
# IND WB DATA EXP MODEL
ind.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2])))
}

# MEAN WB DATA EXP MODEL
mean.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2])))
}

# INV WB DATA EXP MODEL
inv.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))
}

# MEAN INV WB DATA EXP MODEL
mean.inv.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))
}

# INV MEAN WB DATA EXP MODEL
inv.mean.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))
}

# IND WB DATA WB MODEL
ind.wb.wb.med.n <- function(x){
  exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2]))))* (x -
         median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2]))))^2 +
         median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2])))
}

topt.mean.wb.med.n <- data.frame(
  Topt = c(optimize(ind.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.inv.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(ind.wb.wb.med.n, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.inv.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(ind.wb.wb.med.n, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"), levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))
)

# Center point coordinates
center_x.wb.med.n <- topt.mean.wb.med.n$Topt[7]
center_y.wb.med.n <- topt.mean.wb.med.n$Lifetime[7]

# Plotting
ggplot(topt.mean.wb.med.n, aes(x = Topt, y = Lifetime, color = Method)) +
  geom_point() +
  geom_point(x = center_x.wb.med.n, y = center_y.wb.med.n, size = 3, col = plasma(7)[7], shape = 8) +
  labs(title = "Lifetime vs Topt, Narrow Interval (Posterior Median)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Topt", 
       y = "Lifetime") +
  theme_minimal() +
  scale_color_manual(values = plasma(7)) +
  coord_cartesian(xlim = c(center_x.wb.med.n - 1, center_x.wb.med.n + 1), ylim = c(center_y.wb.med.n - 3, center_y.wb.med.n + 3))
```



```{r exp.extreme.mean.narrow}
solve_quadratic.mean <- function(f) {
  # Calculate discriminant
  a <- exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- -2 *
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) *
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- mean(unlist(lapply(f[[3]], function(matrix) matrix[, 1]))) +
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) *
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >= 0) {
    x1 <- (-b + sqrt(discriminant)) / (2 * a)
    x2 <- (-b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}


ext.narrow.df <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve")), 
  Low = c(solve_quadratic.mean(N_param_list1)[2], 
        solve_quadratic.mean(N_param_list2)[2], 
        solve_quadratic.mean(N_param_list3)[2], 
        solve_quadratic.mean(N_param_list4)[2], 
        solve_quadratic.mean(N_param_list5)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.mean(N_param_list1)[1], 
         solve_quadratic.mean(N_param_list2)[1], 
         solve_quadratic.mean(N_param_list3)[1], 
         solve_quadratic.mean(N_param_list4)[1], 
         solve_quadratic.mean(N_param_list5)[1], 
         51.542)
)

center_x.exp.extreme.n <- ext.narrow.df$Low[6]
center_y.exp.extreme.n <- ext.narrow.df$High[6]

# Plotting
ggplot(ext.narrow.df, aes(x = Low, y = High, color = Method)) +
  geom_point() +
  geom_point(x = center_x.exp.extreme.n, y = center_y.exp.extreme.n, size = 3, col = viridis(6)[6], shape = 8) +
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day, Narrow Interval (Posterior Mean)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Low", 
       y = "High") +
  theme_minimal() +
  scale_color_manual(values = viridis(6)) +
  coord_cartesian(xlim = c(center_x.exp.extreme.n - 40, center_x.exp.extreme.n + 40), ylim = c(center_y.exp.extreme.n - 40, center_y.exp.extreme.n + 40))
```

```{r exp.extreme.boxplot.narrow}

df_list.n <- list(df.new1_N, df.new2_N, df.new3_N, df.new4_N, 
                  df.new5_N)

# Lists to store results
x_values_list.n <- list()

for (df_index in 1:length(df_list.n)) {
  df <- df_list.n[[df_index]]
  x_values.n <- numeric()
  
  if (df_index  == 1) {
    a_col <- 3
    b_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    b_col <- 5
    c_col <- 1
  }
  
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    b <- -2 * (df[i, b_col]) * exp(df[i, a_col])
    c <- df[i, c_col] + exp(df[i, a_col]) * (df[i, b_col])^2
    
    # Solve quadratic equation for x when y = 1
    discriminant <- b^2 - 4 * a * (c - 1)
    if (discriminant >= 0) {
      x1.n <- (-b + sqrt(discriminant)) / (2 * a)
      x2.n <- (-b - sqrt(discriminant)) / (2 * a)
      x_values.n <- c(x_values.n, x1.n, x2.n)  
    } else {
      # If discriminant < 0, no real solutions
      warning("No real solutions for y = 1 in quadratic equation.")
    }
  }
  x_values_list.n[[length(x_values_list.n) + 1]] <- x_values.n  
}

double.box.df.ex.n <- data.frame(Low = numeric(), High = numeric())

# Loop through the list
for (i in seq_along(x_values_list.n)) {
  # Extract values from the list
  x_values.n <- x_values_list.n[[i]]
  
  # Create a dataframe with even indices as "low" and odd indices as "high"
  temp_df.n <- data.frame(High = x_values.n[c(TRUE, FALSE)], Low = x_values.n[c(FALSE, TRUE)])
  
  # Bind the dataframe to the result dataframe
  double.box.df.ex.n <- rbind(double.box.df.ex.n, temp_df.n)
}
double.box.df.ex.n <- rbind(double.box.df.ex.n, data.frame(Low = -6.935, 	 High = 51.542))

double.box.df.ex.n$Method <- factor(c(rep("Individual Exp Data, Exp Model", 938), rep("Mean Exp Data, Trunc Norm Model", 938), rep("Individual Inverse Exp Data, Trunc Norm Model", 938), 
               rep("Mean Inverse Exp Data, Trunc Norm Model", 938), rep("Inverse Mean Exp Data, Trunc Norm Model", 938) , "True Curve" 
               )
)



plot.x.ex.n <- ggplot(double.box.df.ex.n, aes(x = Method, y = Low))+
  geom_boxplot()
plot.x.ex.n <- layer_data(plot.x.ex.n)[, 1:6]

plot.y.ex.n <- ggplot(double.box.df.ex.n, aes(x = Method, y = High))+
  geom_boxplot() 
plot.y.ex.n <- layer_data(plot.y.ex.n)[, 1:6]

dub.ex.n<- double.box.df.ex.n |> group_by(Method) |> summarise(medianLow = median(Low), 
                                                     medianHigh = median(High), 
                                                     q1Low = quantile(Low, probs = 0.25), 
                                                     q3Low = quantile(Low, probs = 0.75), 
                                                     q1High = quantile(High, probs = 0.25), 
                                                     q3High = quantile(High, probs = 0.75)) |> 
  mutate(iqrLow = q3Low-q1Low, 
         iqrHigh = q3High-q1High, 
         maxLow = q3Low + 1.5 * iqrLow, 
         minLow = q1Low - 1.5 * iqrLow, 
         maxHigh = q3High+1.5 * iqrHigh, 
         minHigh = q3High-1.5 * iqrHigh, 
         Middle.Low = plot.x.ex.n$middle, 
         Middle.High = plot.y.ex.n$middle)

dub.ex.n$Method <-factor(dub.ex.n$Method, levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

medianLow.True.ex.n <- as.numeric(rep(dub.ex.n[6, 2], 5))
medianHigh.True.ex.n <- as.numeric(rep(dub.ex.n[6, 3], 5))

colnames(plot.x.ex.n) <- paste0("x.", gsub("y", "", colnames(plot.x.ex.n)))
colnames(plot.y.ex.n) <- paste0("y.", gsub("y", "", colnames(plot.y.ex.n)))
df.ex.n <- cbind(plot.x.ex.n, plot.y.ex.n)
df.ex.n$Method <- factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))


ggplot(data = dub.ex.n[1:5, ], aes(fill = Method, color = Method)) +
  scale_fill_manual(values = viridis(5)) +
  scale_color_manual(values = viridis(5)) +
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), 
            color = "black", fill = NA) +
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), alpha = 0.3) +
  geom_segment(aes(x = minLow, y = plot.y.ex.n$y.middle[1:5], xend = maxLow, yend = plot.y.ex.n$y.middle[1:5])) + #whiskers
  geom_segment(aes(x = minLow, y = q1High, xend = minLow, yend = q3High)) + #lower end
  geom_segment(aes(x = maxLow, y = q1High, xend = maxLow, yend = q3High)) + #upper end
  geom_segment(aes(x = plot.x.ex.n$x.middle[1:5], y = minHigh, xend = plot.x.ex.n$x.middle[1:5], yend = maxHigh)) + #whiskers
  geom_segment(aes(x = q1Low, y = minHigh, xend = q3Low, yend = minHigh)) + #lower end
  geom_segment(aes(x = q1Low, y = maxHigh, xend = q3Low, yend = maxHigh)) + #upper end
  theme_classic() +
  #facet_wrap(dub.ex.n$Method[1:5], nrow = 2, scales = "free") +
  geom_point(aes(x = medianLow.True.ex.n, y = medianHigh.True.ex.n), color = "black", show.legend = FALSE) +
  geom_vline(aes(xintercept = medianLow.True.ex.n), color = "black", linetype = "dashed") +
  geom_hline(aes(yintercept = medianHigh.True.ex.n), color = "black", linetype = "dashed") +
  #theme(legend.position = "none") +
  labs(title = "Boxplot of Extreme Temperatures, Narrow Interval", 
       x = "T Lower", 
       y = "T Upper")
ggsave("N_Ex_Temp_Exp.png", width = 8, height = 5)
```

```{r WB.extreme.mean.narrow}
solve_quadratic.mean.wb <- function(f) {
  # Calculate discriminant
  a <- exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- -2 *
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) *
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- mean(unlist(lapply(f[[3]], function(matrix) matrix[, 1]))) +
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) *
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >= 0) {
    x1 <- (-b + sqrt(discriminant)) / (2 * a)
    x2 <- (-b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.narrow.df.mean.wb <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve")), 
  Low = c(solve_quadratic.mean.wb(Weibull_N_param_list1)[2], 
        solve_quadratic.mean.wb(Weibull_N_param_list2)[2], 
        solve_quadratic.mean.wb(Weibull_N_param_list3)[2], 
        solve_quadratic.mean.wb(Weibull_N_param_list4)[2], 
        solve_quadratic.mean.wb(Weibull_N_param_list5)[2], 
        solve_quadratic.mean.wb(Weibull_N_param_list6)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.mean.wb(Weibull_N_param_list1)[1], 
         solve_quadratic.mean.wb(Weibull_N_param_list2)[1], 
         solve_quadratic.mean.wb(Weibull_N_param_list3)[1], 
         solve_quadratic.mean.wb(Weibull_N_param_list4)[1], 
         solve_quadratic.mean.wb(Weibull_N_param_list5)[1], 
         solve_quadratic.mean.wb(Weibull_N_param_list6)[1], 
         51.542)
)

center_x.wb.extreme.n <- ext.narrow.df.mean.wb$Low[7]
center_y.wb.extreme.n <- ext.narrow.df.mean.wb$High[7]

# Plotting
ggplot(ext.narrow.df.mean.wb, aes(x = Low, y = High, color = Method)) +
  geom_point() +
  geom_point(x = center_x.wb.extreme.n, y = center_y.wb.extreme.n, size = 3, col = plasma(7)[7], shape = 8) +
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day, Narrow Interval (Posterior Mean)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Low", 
       y = "High") +
  theme_minimal() +
  scale_color_manual(values = plasma(7)) +
  coord_cartesian(xlim = c(center_x.wb.extreme.n - 10, center_x.wb.extreme.n + 10), ylim = c(center_y.wb.extreme.n - 10, center_y.wb.extreme.n + 10))
```

```{r WB.extreme.boxplot.narrow}

df_list.wb.n <- list(df.new6_W_N, df.new1_W_N, df.new2_W_N, df.new3_W_N, df.new4_W_N, df.new5_W_N)

# Lists to store results
x_values_list.wb.n <- list()

# Loop through dataframes
for (df_index.wb.n in 1:length(df_list.wb.n)) {
  df <- df_list.wb.n[[df_index.wb.n]]
  x_values.wb.n <- numeric()
  
  if (df_index.wb.n  == 2) {
    a_col <- 3
    b_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    b_col <- 5
    c_col <- 1
  }
  
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    b <- -2 * (df[i, b_col]) * exp(df[i, a_col])
    c <- df[i, c_col] + exp(df[i, a_col]) * (df[i, b_col])^2
    
    # Solve quadratic equation for x when y = 1
    discriminant.wb.n <- b^2 - 4 * a * (c - 1)
    if (discriminant.wb.n >= 0) {
      x1.wb.n <- (-b + sqrt(discriminant.wb.n)) / (2 * a)
      x2.wb.n <- (-b - sqrt(discriminant.wb.n)) / (2 * a)
      x_values.wb.n <- c(x_values.wb.n, x1.wb.n, x2.wb.n)  
    } else {
      # If discriminant < 0, no real solutions
      warning("No real solutions for y = 1 in quadratic equation.")
    }
  }
  x_values_list.wb.n[[length(x_values_list.wb.n) + 1]] <- x_values.wb.n 
}

double.box.df.ex.wb.n <- data.frame(Low = numeric(), High = numeric())

# Loop through the list
for (i in seq_along(x_values_list.wb.n)) {
  # Extract values from the list
  x_values.wb.n <- x_values_list.wb.n[[i]]
  
  # Create a dataframe with even indices as "low" and odd indices as "high"
  temp_df.wb.n <- data.frame(High = x_values.wb.n[c(TRUE, FALSE)], Low = x_values.wb.n[c(FALSE, TRUE)])
  
  # Bind the dataframe to the result dataframe
  double.box.df.ex.wb.n <- rbind(double.box.df.ex.wb.n, temp_df.wb.n)
}
double.box.df.ex.wb.n <- rbind(double.box.df.ex.wb.n, data.frame(Low = -6.935, 	 High = 51.542))

double.box.df.ex.wb.n$Method <- factor(c(rep("Individual WB Data, WB Model", 938), rep("Individual WB Data, Exp Model", 938), rep("Mean WB Data, Trunc Norm Model", 938), rep("Individual Inverse WB Data, Trunc Norm Model", 938), 
               rep("Mean Inverse WB Data, Trunc Norm Model", 938), rep("Inverse Mean WB Data, Trunc Norm Model", 938), "True Curve" 
               ), levels = c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "True Curve")
)



plot.x.ex.wb.n <- ggplot(double.box.df.ex.wb.n, aes(x = Method, y = Low))+
  geom_boxplot()
plot.x.ex.wb.n <- layer_data(plot.x.ex.wb.n)[, 1:18]

plot.y.ex.wb.n <- ggplot(double.box.df.ex.wb.n, aes(x = Method, y = High))+
  geom_boxplot() 
plot.y.ex.wb.n <- layer_data(plot.y.ex.wb.n)[, 1:18]

dub.ex.wb.n <- double.box.df.ex.wb.n |> group_by(Method) |> summarise(medianLow = median(Low), 
                                                     medianHigh = median(High), 
                                                     q1Low = quantile(Low, probs = 0.25), 
                                                     q3Low = quantile(Low, probs = 0.75), 
                                                     q1High = quantile(High, probs = 0.25), 
                                                     q3High = quantile(High, probs = 0.75)) |> 
  mutate(iqrLow = q3Low-q1Low, 
         iqrHigh = q3High-q1High, 
         maxLow = q3Low + 1.5 * iqrLow, 
         minLow = q1Low - 1.5 * iqrLow, 
         maxHigh = q3High + 1.5 * iqrHigh, 
         minHigh = q3High - 1.5 * iqrHigh, 
         Middle.Low = plot.x.ex.wb.n$middle, 
         Middle.High = plot.y.ex.wb.n$middle)

dub.ex.wb.n$Method <-factor(dub.ex.wb.n$Method, levels = c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "True Curve"))

medianLow.True.ex.wb.n <- as.numeric(rep(dub.ex.wb.n[7, 2], 6))
medianHigh.True.ex.wb.n <- as.numeric(rep(dub.ex.wb.n[7, 3], 6))

colnames(plot.x.ex.wb.n) <- paste0("x.", gsub("y", "", colnames(plot.x.ex.wb.n)))
colnames(plot.y.ex.wb.n) <- paste0("y.", gsub("y", "", colnames(plot.y.ex.wb.n)))
df.ex.wb.n <- cbind(plot.x.ex.wb.n, plot.y.ex.wb.n)
df.ex.wb.n$Method <- factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "True Curve"))

ggplot(data = dub.ex.wb.n[1:6, ], aes(fill = Method, color = Method)) +
  scale_color_manual(values = plasma(6)) +
  scale_fill_manual(values = plasma(6)) +
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), 
            color = "black", fill = NA) +
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), alpha = 0.3) +
  geom_segment(aes(x = minLow, y = plot.y.ex.wb.n$y.middle[1:6], xend = maxLow, yend = plot.y.ex.wb.n$y.middle[1:6])) + #whiskers
  geom_segment(aes(x = minLow, y = q1High, xend = minLow, yend = q3High)) + #lower end
  geom_segment(aes(x = maxLow, y = q1High, xend = maxLow, yend = q3High)) + #upper end
  geom_segment(aes(x = plot.x.ex.wb.n$x.middle[1:6], y = minHigh, xend = plot.x.ex.wb.n$x.middle[1:6], yend = maxHigh)) + #whiskers
  geom_segment(aes(x = q1Low, y = minHigh, xend = q3Low, yend = minHigh)) + #lower end
  geom_segment(aes(x = q1Low, y = maxHigh, xend = q3Low, yend = maxHigh)) + #upper end
  theme_classic() +
  #facet_wrap(dub.ex.wb.n$Method[1:6], nrow = 2, scales = "free") +
  geom_point(aes(x = medianLow.True.ex.wb.n, y = medianHigh.True.ex.wb.n), color = "black", show.legend = FALSE) +
  geom_vline(aes(xintercept = medianLow.True.ex.wb.n), color = "black", linetype = "dashed") +
  geom_hline(aes(yintercept = medianHigh.True.ex.wb.n), color = "black", linetype = "dashed") +
  #theme(legend.position = "none") +
  labs(title = "Boxplot of Extreme Temperatures, Narrow Interval", 
       x = "T Lower", 
       y = "T Upper")
ggsave("N_Ex_Temp_WB.png", width = 8, height = 5)
```

```{r exp.extreme.med}
solve_quadratic.med <- function(f) {
  # Calculate discriminant
  a <- exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- -2 *
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) *
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- median(unlist(lapply(f[[3]], function(matrix) matrix[, 1]))) +
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) *
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >= 0) {
    x1 <- (-b + sqrt(discriminant)) / (2 * a)
    x2 <- (-b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.narrow.df.med <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve")), 
  Low = c(solve_quadratic.med(N_param_list1)[2], 
        solve_quadratic.med(N_param_list2)[2], 
        solve_quadratic.med(N_param_list3)[2], 
        solve_quadratic.med(N_param_list4)[2], 
        solve_quadratic.med(N_param_list5)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.med(N_param_list1)[1], 
         solve_quadratic.med(N_param_list2)[1], 
         solve_quadratic.med(N_param_list3)[1], 
         solve_quadratic.med(N_param_list4)[1], 
         solve_quadratic.med(N_param_list5)[1], 
         51.542)
)

center_x.exp.extreme.med.n <- ext.narrow.df.med$Low[6]
center_y.exp.extreme.med.n <- ext.narrow.df.med$High[6]

# Plotting
ggplot(ext.narrow.df.med, aes(x = Low, y = High, color = Method)) +
  geom_point() +
  geom_point(x = center_x.exp.extreme.med.n, y = center_y.exp.extreme.med.n, size = 3, col = viridis(6)[6], shape = 8) +
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day, Narrow Interval (Posterior Median)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Low", 
       y = "High") +
  theme_minimal() +
  scale_color_manual(values = viridis(6)) +
  coord_cartesian(xlim = c(center_x.exp.extreme.med.n - 50, center_x.exp.extreme.med.n + 50), ylim = c(center_y.exp.extreme.med.n - 50, center_y.exp.extreme.med.n + 50))

```

```{r WB.extreme.med}
solve_quadratic.med.wb <- function(f) {
  # Calculate discriminant
  a <- exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- -2 *
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) *
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- median(unlist(lapply(f[[3]], function(matrix) matrix[, 1]))) +
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) *
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >= 0) {
    x1 <- (-b + sqrt(discriminant)) / (2 * a)
    x2 <- (-b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.narrow.df.med.wb <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve")), 
  Low = c(solve_quadratic.med.wb(Weibull_N_param_list1)[2], 
        solve_quadratic.med.wb(Weibull_N_param_list2)[2], 
        solve_quadratic.med.wb(Weibull_N_param_list3)[2], 
        solve_quadratic.med.wb(Weibull_N_param_list4)[2], 
        solve_quadratic.med.wb(Weibull_N_param_list5)[2], 
        solve_quadratic.med.wb(Weibull_N_param_list6)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.med.wb(Weibull_N_param_list1)[1], 
         solve_quadratic.med.wb(Weibull_N_param_list2)[1], 
         solve_quadratic.med.wb(Weibull_N_param_list3)[1], 
         solve_quadratic.med.wb(Weibull_N_param_list4)[1], 
         solve_quadratic.med.wb(Weibull_N_param_list5)[1], 
         solve_quadratic.med.wb(Weibull_N_param_list6)[1], 
         51.542)
)

center_x.wb.extreme.med.n <- ext.narrow.df.med.wb$Low[7]
center_y.wb.extreme.med.n <- ext.narrow.df.med.wb$High[7]

# Plotting
ggplot(ext.narrow.df.med.wb, aes(x = Low, y = High, color = Method)) +
  geom_point() +
  geom_point(x = center_x.wb.extreme.med.n, y = center_y.wb.extreme.med.n, size = 3, col = plasma(7)[7], shape = 8) +
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day, Narrow Interval (Posterior Median)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Low", 
       y = "High") +
  theme_minimal() +
  scale_color_manual(values = plasma(7)) +
  coord_cartesian(xlim = c(center_x.wb.extreme.med.n - 10, center_x.wb.extreme.med.n + 10), ylim = c(center_y.wb.extreme.med.n - 10, center_y.wb.extreme.med.n + 10))
```



```{r QQPlot.Ind.Exp.Data.Narrow}
ind.exp.13.n <- qqPlot(N_data.list[[100]]$trait[N_data.list[[100]]$T  == 13], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (13 -
                               median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)
ind.exp.17.n <- qqPlot(N_data.list[[100]]$trait[N_data.list[[100]]$T  == 17], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (17 -
                               median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)
ind.exp.21.n <- qqPlot(N_data.list[[100]]$trait[N_data.list[[100]]$T  == 21], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (21 -
                               median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)
ind.exp.25.n <- qqPlot(N_data.list[[100]]$trait[N_data.list[[100]]$T  == 25], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (25 -
                               median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)
ind.exp.29.n <- qqPlot(N_data.list[[100]]$trait[N_data.list[[100]]$T  == 29], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (29 -
                               median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

png(file="n.ind.exp.qq.png",
    width = 8.5, height = 6, units = "in", res = 250)
plot(ind.exp.13.n, pch = 20, xlim = c(0, 70), ylim = c(0, 100), col = plasma(5)[1], 
     main = "QQ-Plot for Exp Data and Exp Distribution, Narrow Interval", 
       xlab = "Quantiles of Exponential with Posterior Median Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(ind.exp.17.n, pch = 20, col = plasma(5)[2])
points(ind.exp.21.n, pch = 20, col = plasma(5)[3])
points(ind.exp.25.n, pch = 20, col = plasma(5)[4])
points(ind.exp.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Mean.Exp.Data.Narrow}
group_means.mean.exp.n <- tapply(N_data.list[[100]]$trait, N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.exp.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.exp.n)  # Extract means and unlist the result
    )

mean.exp.13.n <- qqPlot(df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (13 -
                               median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list2[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.exp.17.n <- qqPlot(df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (17 -
                               median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list2[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.exp.21.n <- qqPlot(df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (21 -
                               median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list2[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.exp.25.n <- qqPlot(df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (25 -
                               median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list2[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.exp.29.n <- qqPlot(df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (29 -
                               median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list2[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)


png(file="n.mean.exp.qq.png",
    width = 8.5, height = 6, units = "in", res = 250)
plot(mean.exp.13.n, pch = 20, xlim = c(0, 1.5), ylim = c(0, 40), col = plasma(5)[1], 
     main = "QQ-Plot for Mean Exp Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.exp.17.n, pch = 20, col = plasma(5)[2])
points(mean.exp.21.n, pch = 20, col = plasma(5)[3])
points(mean.exp.25.n, pch = 20, col = plasma(5)[4])
points(mean.exp.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.Exp.Data.Narrow}
inv.exp.13.n <- qqPlot(1/N_data.list[[100]]$trait[N_data.list[[100]]$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (13 -
                               median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)
inv.exp.17.n <- qqPlot(1/N_data.list[[100]]$trait[N_data.list[[100]]$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (17 -
                               median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)
inv.exp.21.n <- qqPlot(1/N_data.list[[100]]$trait[N_data.list[[100]]$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (21 -
                               median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)
inv.exp.25.n <- qqPlot(1/N_data.list[[100]]$trait[N_data.list[[100]]$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (25 -
                               median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)
inv.exp.29.n <- qqPlot(1/N_data.list[[100]]$trait[N_data.list[[100]]$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (29 -
                               median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="n.inv.exp.qq.png",
    width = 8.5, height = 6, units = "in", res = 250)
plot(inv.exp.13.n, pch = 20, ylim = c(0, 12), col = plasma(5)[1], 
     main = "QQ-Plot for Inverse Exp Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.exp.17.n, pch = 20, col = plasma(5)[2])
points(inv.exp.21.n, pch = 20, col = plasma(5)[3])
points(inv.exp.25.n, pch = 20, col = plasma(5)[4])
points(inv.exp.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Mean.Inv.Exp.Data.Narrow}
group_means.mean.exp.n <- tapply(N_data.list[[100]]$trait, N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.exp.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.exp.n)  # Extract means and unlist the result
    )

mean.inv.exp.13.n <- qqPlot(1/df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (13 -
                               median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.17.n <- qqPlot(1/df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (17 -
                               median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.21.n <- qqPlot(1/df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (21 -
                               median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.25.n <- qqPlot(1/df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (25 -
                               median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.29.n <- qqPlot(1/df.mean.mean.exp.n$trait[df.mean.mean.exp.n$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (29 -
                               median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)


png(file="n.mean.inv.exp.qq.png",
    width = 8.5, height = 6, units = "in", res = 250)
plot(mean.inv.exp.13.n, pch = 20, xlim = c(0, 50), ylim = c(0, 0.3), col = plasma(5)[1], 
     main = "QQ-Plot for Mean Inverse Exp Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.inv.exp.17.n, pch = 20, col = plasma(5)[2])
points(mean.inv.exp.21.n, pch = 20, col = plasma(5)[3])
points(mean.inv.exp.25.n, pch = 20, col = plasma(5)[4])
points(mean.inv.exp.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.Mean.Exp.Data.Narrow}
group_means.inv.exp.n <- tapply(1/N_data.list[[100]]$trait, N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.inv.exp.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.inv.exp.n)  # Extract means and unlist the result
    )

inv.mean.exp.13.n <- qqPlot(df.mean.inv.exp.n$trait[df.mean.inv.exp.n$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (13 -
                               median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.17.n <- qqPlot(df.mean.inv.exp.n$trait[df.mean.inv.exp.n$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (17 -
                               median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.21.n <- qqPlot(df.mean.inv.exp.n$trait[df.mean.inv.exp.n$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (21 -
                               median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.25.n <- qqPlot(df.mean.inv.exp.n$trait[df.mean.inv.exp.n$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (25 -
                               median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.29.n <- qqPlot(df.mean.inv.exp.n$trait[df.mean.inv.exp.n$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (29 -
                               median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 +
                               median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="n.inv.mean.exp.qq.png",
    width = 8.5, height = 6, units = "in", res = 250)
plot(inv.mean.exp.13.n, pch = 20, xlim = c(0, 1.8), ylim = c(0, 10), col = plasma(5)[1], 
     main = "QQ-Plot for Inverse Mean Exp Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.mean.exp.17.n, pch = 20, col = plasma(5)[2])
points(inv.mean.exp.21.n, pch = 20, col = plasma(5)[3])
points(inv.mean.exp.25.n, pch = 20, col = plasma(5)[4])
points(inv.mean.exp.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```



```{r QQPlot.Ind.WB.Data.Narrow}
ind.wb.13.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 13], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

ind.wb.17.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 17], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

ind.wb.21.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 21], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

ind.wb.25.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 25], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

ind.wb.29.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 29], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

png(file="n.ind.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(ind.wb.13.n, xlim = c(0, 85), ylim = c(0, 35), pch = 20, col = plasma(5)[1], 
       main = "QQ-Plot for WB Data and Exponential Distribution, Narrow Interval", 
       xlab = "Quantiles of Exponential with Posterior Median Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(ind.wb.17.n, pch = 20, col = plasma(5)[2])
points(ind.wb.21.n, pch = 20, col = plasma(5)[3])
points(ind.wb.25.n, pch = 20, col = plasma(5)[4])
points(ind.wb.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.Mean.WB.Data.Narrow}
group_means.mean.wb.n <- tapply(Weibull_N_data.list[[100]]$trait, Weibull_N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })

df.mean.mean.wb.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.wb.n)  # Extract means and unlist the result
    )

mean.wb.13.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 13], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

mean.wb.17.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 17], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

mean.wb.21.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 21], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

mean.wb.25.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 25], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

mean.wb.29.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 29], 
       distribution = "exp", 
       param.list = list(rate = (exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))), plot.it = FALSE)

png(file="n.mean.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.wb.13.n, pch = 20, xlim = c(0, 25), ylim = c(0, 30), col = plasma(5)[1], 
     main = "QQ-Plot for Mean WB Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.wb.17.n, pch = 20, col = plasma(5)[2])
points(mean.wb.21.n, pch = 20, col = plasma(5)[3])
points(mean.wb.25.n, pch = 20, col = plasma(5)[4])
points(mean.wb.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.WB.Data.Narrow}
inv.wb.13.n <- qqPlot(1/Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.17.n <- qqPlot(1/Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.21.n <- qqPlot(1/Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.25.n <- qqPlot(1/Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 25], 
       distribution = "normTrunc",
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.29.n <- qqPlot(1/Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list3[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)


png(file="n.inv.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.wb.13.n, xlim = c(0, 40), ylim = c(0, 0.5), pch = 20, col = plasma(5)[1], 
       main = "QQ-Plot for Inverse WB Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.wb.17.n, pch = 20, col = plasma(5)[2])
points(inv.wb.21.n, pch = 20, col = plasma(5)[3])
points(inv.wb.25.n, pch = 20, col = plasma(5)[4])
points(inv.wb.29.n, pch = 20, col = plasma(5)[5])
legend("bottomright", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.Mean.Inv.WB.Data.Narrow}
group_means.mean.wb.n <- tapply(Weibull_N_data.list[[100]]$trait, Weibull_N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.wb.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.wb.n)  # Extract means and unlist the result
    )

mean.inv.wb.13.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.17.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.21.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.25.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.29.n <- qqPlot(df.mean.mean.wb.n$trait[df.mean.mean.wb.n$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list4[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)


png(file="n.mean.inv.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.inv.wb.13.n, pch = 20, ylim = c(0, 30), xlim = c(0, 160), col = plasma(5)[1], 
       main = "QQ-Plot for Mean Inverse WB Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.inv.wb.17.n, pch = 20, col = plasma(5)[2])
points(mean.inv.wb.21.n, pch = 20, col = plasma(5)[3])
points(mean.inv.wb.25.n, pch = 20, col = plasma(5)[4])
points(mean.inv.wb.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.Inv.Mean.WB.Data.Narrow}
group_means.inv.wb.n <- tapply(1/Weibull_N_data.list[[100]]$trait, Weibull_N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.inv.wb.n <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(group_means.inv.wb.n)  # Extract means and unlist the result
    )

inv.mean.wb.13.n <- qqPlot(df.mean.inv.wb.n$trait[df.mean.inv.wb.n$T  == 13], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.17.n <- qqPlot(df.mean.inv.wb.n$trait[df.mean.inv.wb.n$T  == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.21.n <- qqPlot(df.mean.inv.wb.n$trait[df.mean.inv.wb.n$T  == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.25.n <- qqPlot(df.mean.inv.wb.n$trait[df.mean.inv.wb.n$T  == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.29.n <- qqPlot(df.mean.inv.wb.n$trait[df.mean.inv.wb.n$T  == 29], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2])))), 
                       sd = 1/median(unlist(lapply(Weibull_N_param_list5[[5]], function(matrix) matrix[, 2]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="n.inv.mean.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.mean.wb.13.n, pch = 20, xlim = c(0, 80), ylim = c(0, 0.3), col = plasma(5)[1], 
       main = "QQ-Plot for Inverse Mean WB Data and Trunc Norm Distribution, Narrow Interval", 
       xlab = "Quantiles of Truncated Normal with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.mean.wb.17.n, pch = 20, col = plasma(5)[2])
points(inv.mean.wb.21.n, pch = 20, col = plasma(5)[3])
points(inv.mean.wb.25.n, pch = 20, col = plasma(5)[4])
points(inv.mean.wb.29.n, pch = 20, col = plasma(5)[5])
legend("bottomright", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.WB.Data.WB.Model.Narrow}
wb.wb.13.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 13], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (13 -
                               (median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))/log(2)^(1/median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), 
                         shape = median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), plot.it = FALSE)

wb.wb.17.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 17], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (17 -
                               (median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))/log(2)^(1/median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), 
                         shape = median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), plot.it = FALSE)

wb.wb.21.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 21], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (21 -
                               (median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))/log(2)^(1/median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), 
                         shape = median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), plot.it = FALSE)

wb.wb.25.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 25], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (25 -
                               (median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))/log(2)^(1/median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), 
                         shape = median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), plot.it = FALSE)

wb.wb.29.n <- qqPlot(Weibull_N_data.list[[100]]$trait[Weibull_N_data.list[[100]]$T  == 29], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (29 -
                               (median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2])))))^2 +
                               median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))/log(2)^(1/median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), 
                         shape = median(unlist(lapply(Weibull_N_param_list6[[5]], function(matrix) matrix[, 2])))), plot.it = FALSE)


png(file="n.ind.wb.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(wb.wb.13.n, xlim = c(0, 35), ylim = c(0, 35), pch = 20, col = plasma(5)[1], 
       main = "QQ-Plot for WB Data and WB Distribution, Narrow Interval", 
       xlab = "Quantiles of Weibull with Posterior Median Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(wb.wb.17.n, pch = 20, col = plasma(5)[2])
points(wb.wb.21.n, pch = 20, col = plasma(5)[3])
points(wb.wb.25.n, pch = 20, col = plasma(5)[4])
points(wb.wb.29.n, pch = 20, col = plasma(5)[5])
legend("topleft", legend = c("13", "17", "21", "25", "29"), 
       pch = c(20, 20, 20, 20, 20), col = c(plasma(5)[1], plasma(5)[2], plasma(5)[3], plasma(5)[4], plasma(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```



```{r RMSE.Table.Compare.Narrow}
summary_list.compare_N <- list(
  xdf1_N |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf1_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf6_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf2_N |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf2_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf3_N |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf3_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf4_N |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf4_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf5_N |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf5_W_N |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2)))
)

# Convert the list into a matrix
RMSE.tab.compare_N <- do.call(rbind, summary_list.compare_N)

RMSE.tab.compare_N$Method <- factor(c(
  "Individual Exp Data, Exp Model", 
  "Individual WB Data, Exp Model", 
  "Individual WB Data, WB Model", 
  "Mean Exp Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model"
), 
  levels = c(
  "Individual Exp Data, Exp Model", 
  "Individual WB Data, Exp Model", 
  "Individual WB Data, WB Model", 
  "Mean Exp Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model"
))

RMSE.tab.compare_N

RMSE.tab.compare_N$Set <- factor(c("Exponential", "Weibull", "Weibull", rep(c("Exponential", "Weibull"), 4)))

RMSE.tab.compare_N |> ggplot(aes(x = Method, y = RMSE, fill = Set)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  scale_fill_manual(values = mako(2)) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(RMSE.tab.compare_N$Method))) +
  labs(title = "RMSE Boxplot", 
       subtitle = "Weibull Data") +
  coord_flip() +
  theme_classic()

```

```{r RMSE.mean.param.curve.narrow}
exp.mean.param.curve.rmse.n <- data.frame(
  RMSE = 
    c(sqrt(mean((1/ind.exp.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.exp.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.exp.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.inv.exp.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.mean.exp.n(xseq) - 1/f(xseq))^2)))
)

exp.mean.param.curve.rmse.n$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

wb.mean.param.curve.rmse.n <- data.frame(
  RMSE = 
    c(sqrt(mean((1/ind.wb.med.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.wb.med.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.wb.med.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.inv.wb.med.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.mean.wb.med.n(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/ind.wb.wb.med.n(xseq) - 1/f(xseq))^2)))
)

wb.mean.param.curve.rmse.n$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))

exp.mean.param.curve.rmse.n |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = plasma(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(exp.mean.param.curve.rmse.n$Method))) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Exponential Distribution") +
  theme_minimal()

wb.mean.param.curve.rmse.n |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(wb.mean.param.curve.rmse.n$Method))) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution") +
  theme_minimal()

rbind(exp.mean.param.curve.rmse.n, wb.mean.param.curve.rmse.n) |> ggplot(aes(x = reorder(Method, -RMSE), y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = mako(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  #scale_x_discrete(limits = levels(rbind(exp.mean.param.curve.rmse.n, wb.mean.param.curve.rmse.n)$Method)) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Method") +
  theme_minimal()

```

```{r RMSE.mean.curve.narrow}
exp.mean.curve.rmse.n <- data.frame(
  RMSE = c(sqrt(mean((N_mean.xdf1$med.value.inv - 1/N_mean.xdf1$true_curve)^2)), 
  sqrt(mean((N_mean.xdf2$med.value.inv - 1/N_mean.xdf2$true_curve)^2)), 
  sqrt(mean((N_mean.xdf3$med.value.inv - 1/N_mean.xdf3$true_curve)^2)), 
  sqrt(mean((N_mean.xdf4$med.value.inv - 1/N_mean.xdf4$true_curve)^2)), 
  sqrt(mean((N_mean.xdf5$med.value.inv - 1/N_mean.xdf5$true_curve)^2)))
)

exp.mean.curve.rmse.n$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

wb.mean.curve.rmse.n <- data.frame(
  RMSE = 
    c(sqrt(mean((mean.xdf1_W_N$med.value.inv - log(2)/mean.xdf1_W_N$true_curve)^2)), 
  sqrt(mean((mean.xdf2_W_N$med.value.inv - log(2)/mean.xdf2_W_N$true_curve)^2)), 
  sqrt(mean((mean.xdf3_W_N$med.value.inv - 1/mean.xdf3_W_N$true_curve)^2)), 
  sqrt(mean((mean.xdf4_W_N$med.value.inv - 1/mean.xdf4_W_N$true_curve)^2)), 
  sqrt(mean((mean.xdf5_W_N$med.value.inv - 1/mean.xdf5_W_N$true_curve)^2)), 
  sqrt(mean((mean.xdf6_W_N$med.value.inv - log(2)/mean.xdf6_W_N$true_curve)^2)))
  
)

wb.mean.curve.rmse.n$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))


exp.mean.curve.rmse.n |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = plasma(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(exp.mean.curve.rmse.n$Method))) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Exponential Distribution") +
  theme_minimal()

wb.mean.curve.rmse.n |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(wb.mean.curve.rmse.n$Method))) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution") +
  theme_minimal()

rbind(exp.mean.curve.rmse.n, wb.mean.curve.rmse.n) |> ggplot(aes(x = reorder(Method, -RMSE), y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = mako(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  #scale_x_discrete(limits = levels(rbind(exp.mean.curve.rmse.n, wb.mean.curve.rmse.n)$Method)) +
  coord_flip() +
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Method") +
  theme_minimal()

```

```{r RMSE.data.exp.narrow}
N_data.rmse.ind.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(N_param_list1[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(N_param_list1[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.ind.exp <- bind_rows(N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.ind.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.mean.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(N_param_list2[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(N_param_list2[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.mean.exp <- bind_rows(N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.mean.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.inv.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(N_param_list3[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(N_param_list3[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.inv.exp <- bind_rows(N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.inv.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.mean.inv.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(N_param_list4[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(N_param_list4[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.mean.inv.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.mean.inv.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.inv.mean.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(N_param_list5[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(N_param_list5[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.inv.mean.exp <- bind_rows(N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.inv.mean.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.exp <-  as.data.frame(rbind(N_rmse.ind.exp, 
      N_rmse.mean.exp, 
      N_rmse.inv.exp, 
      N_rmse.mean.inv.exp, 
      N_rmse.inv.mean.exp))
N_data.rmse.exp$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

N_data.rmse.exp |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(N_data.rmse.exp$Method))) +
  coord_flip() +
  labs(title = "RMSE of Data and Posterior Mean Curve", 
       subtitle = "Data Generated from an Exponential Distribution, Narrow Temperature Interval") +
  theme_minimal()
```

```{r RMSE.data.wb.narrow}
N_data.rmse.ind.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list1[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list1[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list1[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.ind.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.ind.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.mean.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list2[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list2[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list2[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.mean.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.mean.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.inv.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list3[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list3[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list3[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.inv.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.inv.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.mean.inv.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list4[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list4[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list4[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.mean.inv.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.mean.inv.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.inv.mean.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list5[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list5[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list5[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.inv.mean.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.inv.mean.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.wb.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(median(unlist(lapply(Weibull_N_param_list6[[1]], function(matrix) matrix[, 2])))) * (temp - 
    median(unlist(lapply(Weibull_N_param_list6[[2]], function(matrix) matrix[, 2]))))^2 + 
    median(unlist(lapply(Weibull_N_param_list6[[3]], function(matrix) matrix[, 2]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
N_rmse.wb.wb <- bind_rows(Weibull_N_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = N_data.rmse.wb.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

N_data.rmse.wb <-  as.data.frame(rbind(N_rmse.ind.wb, 
      N_rmse.mean.wb, 
      N_rmse.inv.wb, 
      N_rmse.mean.inv.wb, 
      N_rmse.inv.mean.wb, 
      N_rmse.wb.wb))
N_data.rmse.wb$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))

N_data.rmse.wb |> ggplot(aes(x = Method, y = RMSE)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) +
  geom_text(aes(label = round(RMSE, 4)), hjust = -0.2, position = position_dodge(width = 0.9)) +
  scale_x_discrete(limits = rev(levels(N_data.rmse.wb$Method))) +
  coord_flip() +
  labs(title = "RMSE of Data and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution, Narrow Temperature Interval") +
  theme_minimal()
```

```{r RMSE.range.exp}
rmse.range.df.n <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model")), 
  Lower.RMSE = c(range(rmse.range.ind.n)[1],
                   range(rmse.range.mean.n)[1],
                   range(rmse.range.inv.n)[1],
                   range(rmse.range.mean.inv.n)[1],
                   range(rmse.range.inv.mean.n)[1]),
  Upper.RMSE = c(range(rmse.range.ind.n)[2],
                   range(rmse.range.mean.n)[2],
                   range(rmse.range.inv.n)[2],
                   range(rmse.range.mean.inv.n)[2],
                   range(rmse.range.inv.mean.n)[2]),
  Average.RMSE = c(mean(rmse.range.ind.n),
                   mean(rmse.range.mean.n),
                   mean(rmse.range.inv.n),
                   mean(rmse.range.mean.inv.n),
                   mean(rmse.range.inv.mean.n))
)

rmse.range.df.n$Method <- factor(rmse.range.df.n$Method, levels = desired_order)
rmse.range.df.n |> ggplot(aes(x = Method)) +
  geom_linerange(aes(ymin = log(Lower.RMSE), ymax = log(Upper.RMSE), x = Method)) +
  geom_point(aes(y = log(Lower.RMSE), color = "Lower RMSE")) +
  geom_point(aes(y = log(Upper.RMSE), color = "Upper RMSE")) +
  geom_point(aes(y = log(Average.RMSE), color = "Average RMSE")) +
  scale_color_manual(values = c("Lower RMSE" = viridis(3)[3], "Upper RMSE" = viridis(3)[1], "Average RMSE" = viridis(3)[2])) +
  coord_flip() +
  labs(y = "Log of RMSE", title = "Range of RMSE Over 100 Models, Narrow Exponential Data") +
  theme_classic() +
  labs(color = " ")
ggsave("rmse.range.exp.n.png", width = 8, height = 4)

rmse.range.df.n |> ggplot(aes(x = Method)) +
  geom_linerange(aes(ymin = Lower.RMSE, ymax = Upper.RMSE, x = Method)) +
  geom_point(aes(y = Lower.RMSE, color = "Lower RMSE")) +
  geom_point(aes(y = Upper.RMSE, color = "Upper RMSE")) +
  geom_point(aes(y = Average.RMSE, color = "Average RMSE")) +
  scale_color_manual(values = c("Lower RMSE" = viridis(3)[3], "Upper RMSE" = viridis(3)[1], "Average RMSE" = viridis(3)[2])) +
  coord_flip() +
  labs(y = "Log of RMSE", title = "Range of RMSE Over 100 Models") +
  theme_classic() +
  labs(color = " ")
```

```{r RMSE.range.wb}
rmse.range.df.wb.n <- data.frame(
  Method = factor(c("Individual WB Data, WB Model", "Individual WB Data, Exp Model", "Mean WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model")), 
  Lower.RMSE = c(range(rmse.range.ind.wb.wb.n)[1],
                 range(rmse.range.ind.wb.n)[1],
                   range(rmse.range.mean.wb.n)[1],
                   range(rmse.range.inv.wb.n)[1],
                   range(rmse.range.mean.inv.wb.n)[1],
                   range(rmse.range.inv.mean.wb.n)[1]),
  Upper.RMSE = c(range(rmse.range.ind.wb.wb.n)[2],
                 range(rmse.range.ind.wb.n)[2],
                   range(rmse.range.mean.wb.n)[2],
                   range(rmse.range.inv.wb.n)[2],
                   range(rmse.range.mean.inv.wb.n)[2],
                   range(rmse.range.inv.mean.wb.n)[2]),
  Average.RMSE = c(mean(rmse.range.ind.wb.wb.n),
                   mean(rmse.range.ind.wb.n),
                   mean(rmse.range.mean.wb.n),
                   mean(rmse.range.inv.wb.n),
                   mean(rmse.range.mean.inv.wb.n),
                   mean(rmse.range.inv.mean.wb.n))
)

rmse.range.df.wb.n$Method <- factor(rmse.range.df.wb.n$Method, levels = desired_order.wb)
rmse.range.df.wb.n |> ggplot(aes(x = Method)) +
  geom_linerange(aes(ymin = log(Lower.RMSE), ymax = log(Upper.RMSE), x = Method)) +
  geom_point(aes(y = log(Lower.RMSE), color = "Lower RMSE")) +
  geom_point(aes(y = log(Upper.RMSE), color = "Upper RMSE")) +
  geom_point(aes(y = log(Average.RMSE), color = "Average RMSE")) +
  scale_color_manual(values = c("Lower RMSE" = viridis(3)[3], "Upper RMSE" = viridis(3)[1], "Average RMSE" = viridis(3)[2])) +
  coord_flip() +
  labs(y = "Log of RMSE", title = "Range of RMSE Over 100 Models, Narrow Weibull Data") +
  theme_classic() +
  labs(color = " ")
ggsave("rmse.range.wb.n.png", width = 8, height = 4)

rmse.range.df.wb.n |> ggplot(aes(x = Method)) +
  geom_linerange(aes(ymin = Lower.RMSE, ymax = Upper.RMSE, x = Method)) +
  geom_point(aes(y = Lower.RMSE, color = "Lower RMSE")) +
  geom_point(aes(y = Upper.RMSE, color = "Upper RMSE")) +
  geom_point(aes(y = Average.RMSE, color = "Average RMSE")) +
  scale_color_manual(values = c("Lower RMSE" = viridis(3)[3], "Upper RMSE" = viridis(3)[1], "Average RMSE" = viridis(3)[2])) +
  coord_flip() +
  labs(y = "Log of RMSE", title = "Range of RMSE Over 100 Models") +
  theme_classic() +
  labs(color = " ")
```



```{r n.data.example.exp}
N_data.list[[100]]$inv.trait <- 1/N_data.list[[100]]$trait
n.group_means.plot <- tapply(N_data.list[[100]]$trait, N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
n.df.mean.plot <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(n.group_means.plot)  # Extract means and unlist the result
    )
n.group_means.inv.plot <- tapply(N_data.list[[100]]$inv.trait, N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
n.df.mean.inv.plot <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(n.group_means.inv.plot)  # Extract means and unlist the result
    )


n.ind.plot <- ggplot(N_data.list[[100]], aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime") + 
  theme_classic()
ggsave("n.ind.plot.png", plot = n.ind.plot, width = 3, height = 3)
n.mean.plot <- ggplot(n.df.mean.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime") + 
  theme_classic()
ggsave("n.mean.plot.png", plot = n.mean.plot, width = 3, height = 3)
n.inv.plot <- ggplot(N_data.list[[100]], aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.inv.plot.png", plot = n.inv.plot, width = 3, height = 3)
n.mean.inv.plot <- ggplot(n.df.mean.plot, aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.mean.inv.plot.png", plot = n.mean.inv.plot, width = 3, height = 3)
n.inv.mean.plot <- ggplot(n.df.mean.inv.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.inv.mean.plot.png", plot = n.inv.mean.plot, width = 3, height = 3)

```

```{r n.data.example.wb}
Weibull_N_data.list[[100]]$inv.trait <- 1/Weibull_N_data.list[[100]]$trait
n.wb.group_means.plot <- tapply(Weibull_N_data.list[[100]]$trait, Weibull_N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
n.wb.df.mean.plot <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(n.wb.group_means.plot)  # Extract means and unlist the result
    )
n.wb.group_means.inv.plot <- tapply(Weibull_N_data.list[[100]]$inv.trait, Weibull_N_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
n.wb.df.mean.inv.plot <- data.frame(
    T = c(rep(13, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(29, 10)), # Extract T values as numeric
    trait = unlist(n.wb.group_means.inv.plot)  # Extract means and unlist the result
    )


n.wb.ind.plot <- ggplot(Weibull_N_data.list[[100]], aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime") + 
  theme_classic()
ggsave("n.wb.ind.plot.png", plot = n.wb.ind.plot, width = 3, height = 3)
n.wb.mean.plot <- ggplot(n.wb.df.mean.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime") + 
  theme_classic()
ggsave("n.wb.mean.plot.png", plot = n.wb.mean.plot, width = 3, height = 3)
n.wb.inv.plot <- ggplot(Weibull_N_data.list[[100]], aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.wb.inv.plot.png", plot = n.wb.inv.plot, width = 3, height = 3)
n.wb.mean.inv.plot <- ggplot(n.wb.df.mean.plot, aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.wb.mean.inv.plot.png", plot = n.wb.mean.inv.plot, width = 3, height = 3)
n.wb.inv.mean.plot <- ggplot(n.wb.df.mean.inv.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime") + 
  theme_classic()
ggsave("n.wb.inv.mean.plot.png", plot = n.wb.inv.mean.plot, width = 3, height = 3)

```

