 -  -  - 
title: "Collection of Tick Simulation"
author: "Piper Zimmerman"
date: "December 12, 2023"
output: pdf_document
 -  -  - 

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(ggplot2)
library(EnvStats)
```

```{r load.wide.exp, eval = FALSE}
load("individual_exponential.RData")
load("mean_exponential.RData")
load("inverse_exponential.RData")
load("mean_inverse_exponential.RData")
load("inverse_mean_exponential.RData")
load("inverse_notrunc.RData")
load("mean_inverse_notrunc.RData")
load("inverse_mean_notrunc.RData")
```

```{r load.wide.wb, eval = FALSE}
load("Weibull_individual.RData")
load("Weibull_mean.RData")
load("Weibull_inverse.RData")
load("Weibull_mean_inverse.RData")
load("Weibull_inverse_mean.RData")
load("Weibull_weibull_data.RData")
```


```{r plot.a.wide}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

df.a <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Median = c(exp(median(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a$x <- factor(df.a$x, levels = desired_order)
a.plot <- ggplot(df.a, aes(x, Median)) + 
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) + 
  labs(title = "Parameter a", x = "Method") + 
  geom_hline(yintercept = true.a, linetype = "dashed", color = cividis(3)[3]) + 
  theme_classic() + 
  coord_flip()
a.plot
ggsave("a.comp.exp.png", plot = a.plot, width = 8, height = 5)
```

```{r plot.Topt.wide}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

df.b <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Median = c(median(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[1])
)
df.b$x <- factor(df.b$x, levels = desired_order)
b.plot <- ggplot(df.b, aes(x, Median)) + 
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) + 
  labs(title = "Parameter Topt", x = "Method") + 
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = cividis(3)[3]) + 
  theme_classic() + 
  coord_flip()
b.plot
ggsave("Topt.comp.exp.png", plot = b.plot, width = 8, height = 5)
```

```{r plot.c.wide}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

df.c <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Median = c((median(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c$x <- factor(df.c$x, levels = desired_order)
c.plot <- ggplot(df.c, aes(x, Median)) + 
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = cividis(3)[2]) + 
  labs(title = "Parameter c", x = "Method") + 
  geom_hline(yintercept = true.c, linetype = "dashed", color = cividis(3)[3]) + 
  theme_classic() + 
  coord_flip()
c.plot
ggsave("c.comp.exp.png", plot = c.plot, width = 8, height = 5)
```

```{r plot.a.wide.log}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

log_df.a <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Mean = c(exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[1]))
)
log_df.a$x <- factor(log_df.a$x, levels = desired_order)
log_a.plot <- ggplot(log_df.a, aes(x, log(Mean))) + 
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) + 
  labs(title = "A", x = "Method") + 
  geom_hline(yintercept = log(true.a), linetype = "dashed", color = "black") + 
  theme_classic() + 
  labs(y = "Log of Posterior Mean") + 
  coord_flip()
log_a.plot
ggsave("a_exp_compare.png", plot = log_a.plot, width = 10, height = 7)
```

```{r plot.Topt.wide.log}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

log_df.b <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Mean = c(mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[1])
)
log_df.b$x <- factor(log_df.b$x, levels = desired_order)
log_b.plot <- ggplot(log_df.b, aes(x, log(Mean))) + 
  geom_point(col = cividis(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) + 
  labs(title = "Topt", x = "Method") + 
  geom_hline(yintercept = log(true.Topt), linetype = "dashed", color = cividis(3)[3]) + 
  theme_classic() + 
  coord_flip()
log_b.plot
```

```{r plot.c.wide.log}
desired_order <- c("Inverse Mean Exp Data, Exp Model", "Mean Inverse Exp Data, Exp Model", 
                      "Individual Inverse Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model")

log_df.c <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Exp Model", 
               "Mean Inverse Exp Data, Exp Model", "Inverse Mean Exp Data, Exp Model")), 
  Mean = c((mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[1]))
)
log_df.c$x <- factor(log_df.c$x, levels = desired_order)
log_c.plot <- ggplot(log_df.c, aes(x, log(Mean))) + 
  geom_point(col =  cividis(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = cividis(3)[2]) + 
  labs(title = "C", x = "Method") + 
  geom_hline(yintercept = log(true.c), linetype = "dashed", color = cividis(3)[3]) + 
  theme_classic() + 
  coord_flip()
log_c.plot
```



```{r plot.a.wide.wb}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Exp Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")

df.a.wb <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "Inverse Mean WB Data, Exp Model", "WB Data, WB Model")), 
  Median = c(exp(median(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(median(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a.wb$x <- factor(df.a.wb$x, levels = desired_order.wb)
a.wb.plot <- ggplot(df.a.wb, aes(x, Median)) + 
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) + 
  labs(title = "Parameter a", x = "Method") + 
  geom_hline(yintercept = true.a, linetype = "dashed", color = plasma(3)[3]) + 
  theme_classic() + 
  coord_flip()
a.wb.plot
ggsave("a.comp.wb.png", plot = a.wb.plot, width = 8, height = 5)
```

```{r plot.Topt.wide.wb}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Exp Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")

df.b.wb <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "Inverse Mean WB Data, Exp Model", "WB Data, WB Model")), 
  Median = c(median(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1]))), 
           median(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[1])
)
df.b.wb$x <- factor(df.b.wb$x, levels = desired_order.wb)
b.wb.plot <- ggplot(df.b.wb, aes(x, Median)) + 
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) + 
  labs(title = "Parameter Topt", x = "Method") + 
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = plasma(3)[3]) + 
  theme_classic() + 
  coord_flip()
b.wb.plot
ggsave("Topt.comp.wb.png", plot = b.wb.plot, width = 8, height = 5)
```

```{r plot.c.wide.wb}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Exp Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.c.wb <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "Inverse Mean WB Data, Exp Model", "WB Data, WB Model")), 
  Median = c((median(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (median(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c.wb$x <- factor(df.c.wb$x, levels = desired_order.wb)
c.wb.plot <- ggplot(df.c.wb, aes(x, Median)) + 
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = plasma(3)[2]) + 
  labs(title = "Parameter c", x = "Method") + 
  geom_hline(yintercept = true.c, linetype = "dashed", color = "black") + 
  theme_classic() + 
  coord_flip()
c.wb.plot
ggsave("c.comp.wb.png", plot = c.wb.plot, width = 8, height = 5)
```

```{r plot.a.wide.wb.log}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Exp Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.a.wb.log <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "Inverse Mean WB Data, Exp Model", "WB Data, WB Model")), 
  Mean = c(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1]))))), 
  upper = c(exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[2])), 
  lower = c(exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a.wb.log$x <- factor(df.a.wb.log$x, levels = desired_order.wb)
a.wb.log.plot <- ggplot(df.a.wb.log, aes(x, log(Mean))) + 
  geom_point(col = plasma(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) + 
  labs(title = "A", x = "Method") + 
  geom_hline(yintercept = log(true.exp.a), linetype = "dashed", color = plasma(3)[3]) + 
  theme_classic() + 
  coord_flip()
a.wb.log.plot
```

```{r plot.Topt.wide.wb.log}
desired_order.wb <- c("WB Data, WB Model", "Inverse Mean WB Data, Exp Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.b.wb.log <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "Inverse Mean WB Data, Exp Model", "WB Data, WB Model")), 
  Mean = c(mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1]))), 
           mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))), 
  upper = c(hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[2], 
            hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[2]), 
  lower = c(hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[1], 
            hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[1])
)
df.b.wb.log$x <- factor(df.b.wb.log$x, levels = desired_order.wb)
b.wb.log.plot <- ggplot(df.b.wb.log, aes(x, log(Mean))) + 
  geom_point(col = plasma(3)[1]) +
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) + 
  labs(title = "Topt", x = "Method") + 
  geom_hline(yintercept = log(true.Topt), linetype = "dashed", color = plasma(3)[3]) + 
  theme_classic() + 
  coord_flip()
b.wb.log.plot
```

```{r plot.c.wide.wb.log}
desired_order.wb <- c("WB Data, WB Model", "Mean Inverse WB Data, Exp Model", 
                      "Individual Inverse WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual WB Data, Exp Model")
df.c.wb.log <- data.frame(
  x = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Exp Model", 
               "Mean Inverse WB Data, Exp Model", "WB Data, WB Model")), 
  Mean = c((mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
           #(mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))), 
  upper = c((hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            #(hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[2])), 
  lower = c((hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            #(hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c.wb.log$x <- factor(df.c.wb.log$x, levels = desired_order.wb)
c.wb.log.plot <- ggplot(df.c.wb.log, aes(x, log(Mean))) + 
  geom_point(col =  plasma(3)[1]) + 
  geom_linerange(aes(ymin = log(lower), ymax = log(upper)), col = plasma(3)[2]) + 
  labs(title = "C", x = "Method") + 
  geom_hline(yintercept = log(true.exp.c), linetype = "dashed", color = "black") + 
  theme_classic() + 
  labs(y = "Log of Posterior Mean") + 
  coord_flip()
c.wb.log.plot
ggsave("c_wb_compare.png", plot = c.wb.log.plot, width = 10)
```



```{r plot.a.wide.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.a.compare <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model",  "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))), 
           exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1]))))), 
  
  upper = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[2]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c(exp(hdi(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))[1]), 
            exp(hdi(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))[1]))
)
df.a.compare$x <- factor(df.a.compare$x, levels = desired_order.compare)
a.compare.plot <- ggplot(df.a.compare, aes(x, Mean)) + 
  geom_point(col = viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) + 
  labs(title = "A", x = "Method") + 
  geom_hline(yintercept = true.a, linetype = "dashed", color = viridis(3)[3]) + 
  theme_classic() + 
  coord_flip()
a.compare.plot
```

```{r plot.Topt.wide.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.b.compare <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model",  "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c(mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))), 
           mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))), 
           (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1]))))), 
  
  upper = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[2]), 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[2], 
            (hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c(hdi(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))[1]), 
            hdi(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1])))[1], 
            (hdi(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))[1]))
)
df.b.compare$x <- factor(df.b.compare$x, levels = desired_order.compare)
b.compare.plot <- ggplot(df.b.compare, aes(x, Mean)) + 
  geom_point(col =  viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) + 
  labs(title = "Topt", x = "Method") + 
  geom_hline(yintercept = true.Topt, linetype = "dashed", color = viridis(3)[3]) + 
  theme_classic() + 
  coord_flip()
b.compare.plot
```

```{r plot.c.wide.compare}
desired_order.compare <- c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
                         "Mean Inverse WB Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", 
                         "Individual Inverse WB Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
                         "Mean WB Data, Exp Model", "Mean Exp Data, Exp Model", "Individual WB Data, Exp Model", "Individual Exp Data, Exp Model")
df.c.compare <- data.frame(
  x = factor(c("Individual Exp Data, Exp Model", "Individual WB Data, Exp Model", "Mean Exp Data, Exp Model", "Mean WB Data, Exp Model", 
               "Individual Inverse Exp Data, Trunc Norm Model",  "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model")), 
  Mean = c((mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
           (mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))), 
  
  upper = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[2]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[2])), 
  
  lower = c((hdi(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))[1]), 
            (hdi(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))[1]))
)
df.c.compare$x <- factor(df.c.compare$x, levels = desired_order.compare)
c.compare.plot <- ggplot(df.c.compare, aes(x, Mean)) + 
  geom_point(col = viridis(3)[1]) + 
  geom_linerange(aes(ymin = lower, ymax = upper), col = viridis(3)[2]) + 
  labs(title = "C", x = "Method") + 
  geom_hline(yintercept = true.c, linetype = "dashed", col = viridis(3)[3]) + 
  theme_classic() + 
  coord_flip()
c.compare.plot
```



```{r exp.topt.maxlife.mean}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND EXP DATA EXP MODEL
ind.exp <- function(x){
  (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))
}

# MEAN EXP DATA EXP MODEL
mean.exp <- function(x){
  (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))
}

# INV EXP DATA EXP MODEL
inv.exp <- function(x){
  (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1]))))
}

# MEAN INV EXP DATA EXP MODEL
mean.inv.exp <- function(x){
  (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1]))))
}

# INV MEAN EXP DATA EXP MODEL
inv.mean.exp <- function(x){
  (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1]))))
}

topt.mean.exp <- data.frame(
  Topt = c(optimize(ind.exp, interval = c( - 100, 200))$minimum, 
         optimize(mean.exp, interval = c( - 100, 200))$minimum, 
         optimize(inv.exp, interval = c( - 100, 200))$minimum, 
         optimize(mean.inv.exp, interval = c( - 100, 200))$minimum, 
         optimize(inv.mean.exp, interval = c( - 100, 200))$minimum, 
         optimize(f, interval = c( - 100, 200))$minimum), 
  Lifetime = c(1/optimize(ind.exp, interval = c( - 100, 200))$objective, 
            1/optimize(mean.exp, interval = c( - 100, 200))$objective, 
            1/optimize(inv.exp, interval = c( - 100, 200))$objective, 
            1/optimize(mean.inv.exp, interval = c( - 100, 200))$objective, 
            1/optimize(inv.mean.exp, interval = c( - 100, 200))$objective, 
            1/optimize(f, interval = c( - 100, 200))$objective
            ), 
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))
)

# Center point coordinates
center_x.exp <- topt.mean.exp$Topt[6]
center_y.exp <- topt.mean.exp$Lifetime[6]

# Plotting
ggplot(topt.mean.exp, aes(x = Topt, y = Lifetime, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.exp, y = center_y.exp, size = 3, col = viridis(6)[6], shape = 8)  + 
  labs(title = "Lifetime vs Topt (Posterior Mean)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Topt", 
       y = "Lifetime")  + 
  theme_minimal() + 
  scale_color_manual(values = viridis(6)) + 
  coord_cartesian(xlim = c(center_x.exp - 1, center_x.exp + 1), ylim = c(center_y.exp - 10, center_y.exp + 10))

```

```{r exp.topt.maxlife.boxplot}
evaluate_expression <- function(x, a, Topt, c) {
  result <- a * (x - Topt)^2 + c
  return(result)
}

df_list <- list(df.new1, df.new2, df.new3, df.new4, df.new5)
min_x_values_list <- list()
min_values_list <- list()

for (df_index in 1:length(df_list)) {
  df <- df_list[[df_index]]
  min_x_values <- numeric()
  min_values <- numeric()
  
  if (df_index  ==  1 || df_index  ==  2) {
    a_col <- 3
    Topt_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    Topt_col <- 5
    c_col <- 1
  }
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    Topt <- df[i, Topt_col]
    c <- df[i, c_col]
    responses <- evaluate_expression(xseq, a, Topt, c)
    min_x <- xseq[which.min(responses)]
    min_value <- min(responses)
    min_x_values <- c(min_x_values, min_x)
    min_values <- c(min_values, min_value)
  }
  min_x_values_list[[length(min_x_values_list) + 1]] <- min_x_values
  min_values_list[[length(min_values_list) + 1]] <- min_values
}

double.box.df <- data.frame(
  Topt = c(min_x_values_list[[1]], 
           min_x_values_list[[2]], 
           min_x_values_list[[3]], 
           min_x_values_list[[4]], 
           min_x_values_list[[5]], 
           23.3), 
  Lifetime = c(1/min_values_list[[1]], 
               1/min_values_list[[2]], 
               1/min_values_list[[3]], 
               1/min_values_list[[4]], 
               1/min_values_list[[5]], 
               15.433231), 
  Method = factor(c(rep("Individual Exp Data, Exp Model", 938), rep("Mean Exp Data, Exp Model", 938), rep("Individual Inverse Exp Data, Trunc Norm Model", 938), 
               rep("Mean Inverse Exp Data, Trunc Norm Model", 938), rep("Inverse Mean Exp Data, Trunc Norm Model", 938), "True Curve")
               )
)

plot.x <- ggplot(double.box.df, aes(x =  Method, y =  Topt)) + 
  geom_boxplot()
plot.x <- layer_data(plot.x)[, 1:6]

plot.y <- ggplot(double.box.df, aes(x =  Method, y =  Lifetime)) + 
  geom_boxplot() 
plot.y <- layer_data(plot.y)[, 1:6]

dub <- double.box.df |> group_by(Method) |> summarise(medianTopt = median(Topt), 
                                                     medianLife = median(Lifetime), 
                                                     q1Topt = quantile(Topt, probs = 0.25), 
                                                     q3Topt = quantile(Topt, probs = 0.75), 
                                                     q1Life = quantile(Lifetime, probs = 0.25), 
                                                     q3Life = quantile(Lifetime, probs = 0.75)) |> 
  mutate(iqrTopt = q3Topt - q1Topt, 
         iqrLife = q3Life - q1Life, 
         maxTopt = q3Topt + 1.5 * iqrTopt, 
         minTopt = q1Topt - 1.5 * iqrTopt, 
         maxLife = q3Life + 1.5 * iqrLife, 
         minLife = q1Life - 1.5 * iqrLife, 
         Middle.Topt = plot.x$middle, 
         Middle.Life = plot.y$middle)

dub$Method <- factor(dub$Method, levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

medianTopt.True <- as.numeric(rep(dub[6, 2], 5))
medianLife.True <- as.numeric(rep(dub[6, 3], 5))

colnames(plot.x) <- paste0("x.", gsub("y", "", colnames(plot.x)))
colnames(plot.y) <- paste0("y.", gsub("y", "", colnames(plot.y)))
df <- cbind(plot.x, plot.y)
df$Method <- factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

ggplot(data = dub[1:5, ], aes(fill = Method, color = Method))  + 
  scale_color_manual(values = viridis(5)) + 
  scale_fill_manual(values = viridis(5)) + 
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), 
            color = "black", fill = NA)  + 
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), alpha = 0.3)  + 
  geom_segment(aes(x = minTopt, y = plot.y$y.middle[1:5], xend = maxTopt, yend = plot.y$y.middle[1:5])) + #whiskers
  geom_segment(aes(x = minTopt, y = q1Life, xend = minTopt, yend = q3Life)) + #lower end
  geom_segment(aes(x = maxTopt, y = q1Life, xend = maxTopt, yend = q3Life)) + #upper end
  geom_segment(aes(x = plot.x$x.middle[1:5], y = minLife, xend = plot.x$x.middle[1:5], yend = maxLife)) + #whiskers
  geom_segment(aes(x = q1Topt, y = minLife, xend = q3Topt, yend = minLife)) + #lower end
  geom_segment(aes(x = q1Topt, y = maxLife, xend = q3Topt, yend = maxLife)) + #upper end
  theme_classic() + 
  #facet_wrap(dub$Method[1:5], nrow = 2) + 
  geom_point(aes(x = medianTopt.True, y =  medianLife.True), color = "black", show.legend = FALSE) + 
  #theme(legend.position = "none") + 
  labs(title =  "Boxplot of Topt and Lifetime", 
       x = "Topt", 
       y = "Lifetime")
ggsave("Topt_Life_Exp.png", width = 8, height = 5)
```

```{r WB.topt.maxlife.mean}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND WB DATA EXP MODEL
ind.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1])))
}

# MEAN WB DATA EXP MODEL
mean.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1])))
}

# INV WB DATA EXP MODEL
inv.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))
}


# MEAN INV WB DATA EXP MODEL
mean.inv.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))
}


# INV MEAN WB DATA EXP MODEL
inv.mean.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))
}


# IND WB DATA WB MODEL
ind.wb.wb <- function(x){
  exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (x - 
         mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1]))))^2  + 
         mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1])))
}

topt.mean.wb <- data.frame(
  Topt = c(optimize(ind.wb, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.wb, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.wb, interval = c( - 100, 200))$minimum, 
         optimize(mean.inv.wb, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.wb, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(ind.wb.wb, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.wb, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.wb, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.wb, interval = c( - 100, 200))$objective, 
            1/optimize(mean.inv.wb, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.wb, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(ind.wb.wb, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"), levels =  c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))
)

# Center point coordinates
center_x.wb <- topt.mean.wb$Topt[7]
center_y.wb <- topt.mean.wb$Lifetime[7]

# Plotting
ggplot(topt.mean.wb, aes(x = Topt, y = Lifetime, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.wb, y = center_y.wb, size = 3, col = plasma(7)[7], shape = 8)  + 
  labs(title = "Lifetime vs Topt (Posterior Mean)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Topt", 
       y = "Lifetime")  + 
  theme_minimal() + 
  scale_color_manual(values = plasma(7)) + 
  coord_cartesian(xlim = c(center_x.wb - 1, center_x.wb + 1), ylim = c(center_y.wb - 3, center_y.wb + 3))
```

```{r WB.topt.maxlife.boxplot}
evaluate_expression <- function(x, a, Topt, c) {
  result <- a * (x - Topt)^2 + c
  return(result)
}


df_list.wb <- list(df.new1_W, df.new2_W, df.new3_W, df.new4_W, df.new5_W, df.new6_W)
min_x_values_list.wb <- list()
min_values_list.wb <- list()

for (df_index.wb in 1:length(df_list.wb)) {
  df.wb <- df_list.wb[[df_index.wb]]
  min_x_values.wb <- numeric()
  min_values.wb <- numeric()
  
  if (df_index.wb  ==  1 || df_index.wb  ==  2) {
    a_col <- 3
    Topt_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    Topt_col <- 5
    c_col <- 1
  }
  for (i in 1:nrow(df.wb)) {
    a <- exp(df.wb[i, a_col])
    Topt <- df.wb[i, Topt_col]
    c <- df.wb[i, c_col]
    responses.wb <- evaluate_expression(xseq, a, Topt, c)
    min_x.wb <- xseq[which.min(responses.wb)]
    min_value.wb <- min(responses.wb)
    min_x_values.wb <- c(min_x_values.wb, min_x.wb)
    min_values.wb <- c(min_values.wb, min_value.wb)
  }
  min_x_values_list.wb[[length(min_x_values_list.wb) + 1]] <- min_x_values.wb
  min_values_list.wb[[length(min_values_list.wb) + 1]] <- min_values.wb
}



double.box.df.wb <- data.frame(
  Topt = c(min_x_values_list.wb[[1]], 
           min_x_values_list.wb[[2]], 
           min_x_values_list.wb[[3]], 
           min_x_values_list.wb[[4]], 
           min_x_values_list.wb[[5]], 
           min_x_values_list.wb[[6]], 
           22.3), 
  Lifetime = c(1/min_values_list.wb[[1]], 
               1/min_values_list.wb[[2]], 
               1/min_values_list.wb[[3]], 
               1/min_values_list.wb[[4]], 
               1/min_values_list.wb[[5]], 
               1/min_values_list.wb[[6]], 
               15.433231), 
  Method = factor(c(rep("Individual WB Data, Exp Model", 938), rep("Mean WB Data, Exp Model", 938), rep("Individual Inverse WB Data, Trunc Norm Model", 938), 
               rep("Mean Inverse WB Data, Trunc Norm Model", 938), rep("Inverse Mean WB Data, Trunc Norm Model", 938), rep("Individual WB Data, WB Model", 938), "True Curve"), 
               levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "Individual WB Data, WB Model", 
                "True Curve")
               )
)
plot.x.wb <- ggplot(double.box.df.wb, aes(x =  Method, y =  Topt)) + 
  geom_boxplot()
plot.x.wb <- layer_data(plot.x.wb)[, 1:6]

plot.y.wb <- ggplot(double.box.df.wb, aes(x =  Method, y =  Lifetime)) + 
  geom_boxplot() 
plot.y.wb <- layer_data(plot.y.wb)[, 1:6]

colnames(plot.x.wb) <- paste0("x.", gsub("y", "", colnames(plot.x.wb)))
colnames(plot.y.wb) <- paste0("y.", gsub("y", "", colnames(plot.y.wb)))
df.wb <- cbind(plot.x.wb, plot.y.wb)
df.wb$Method <- factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "Individual WB Data, WB Model", 
                "True Curve"))

dub.wb <- double.box.df.wb |> group_by(Method) |> summarise(medianTopt = median(Topt), 
                                                     medianLife = median(Lifetime), 
                                                     q1Topt = quantile(Topt, probs = 0.25), 
                                                     q3Topt = quantile(Topt, probs = 0.75), 
                                                     q1Life = quantile(Lifetime, probs = 0.25), 
                                                     q3Life = quantile(Lifetime, probs = 0.75)) |> 
  mutate(iqrTopt = q3Topt - q1Topt, 
         iqrLife = q3Life - q1Life, 
         maxTopt = q3Topt + 1.5 * iqrTopt, 
         minTopt = q1Topt - 1.5 * iqrTopt, 
         maxLife = q3Life + 1.5 * iqrLife, 
         minLife = q1Life - 1.5 * iqrLife, 
         Middle.Topt = plot.x.wb$middle, 
         Middle.Life = plot.y.wb$middle, )
dub.wb$Method <- factor(dub.wb$Method, levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "Individual WB Data, WB Model", 
                "True Curve"))
medianTopt.True.wb <- as.numeric(rep(dub.wb[7, 2], 6))
medianLife.True.wb <- as.numeric(rep(dub.wb[7, 3], 6))

plot.x.wb[6,3] <- (plot.x.wb[6,2] + plot.x.wb[6,4])/2
ggplot(data = dub.wb[1:6, ], aes(fill = Method, color = Method))  + 
  scale_color_manual(values = plasma(6)) + 
  scale_fill_manual(values = plasma(6)) + 
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), 
            color = "black", fill = NA)  + 
  geom_rect(aes(xmin = q1Topt, xmax = q3Topt, ymin = q1Life, ymax = q3Life), alpha = 0.3)  + 
  geom_segment(aes(x = minTopt, y = plot.y.wb$y.middle[1:6], xend = maxTopt, yend = plot.y.wb$y.middle[1:6])) + #whiskers
  geom_segment(aes(x = minTopt, y = q1Life, xend = minTopt, yend = q3Life)) + #lower end
  geom_segment(aes(x = maxTopt, y = q1Life, xend = maxTopt, yend = q3Life)) + #upper end
  geom_segment(aes(x = plot.x.wb$x.middle[1:6], y = minLife, xend = plot.x.wb$x.middle[1:6], yend = maxLife)) + #whiskers
  geom_segment(aes(x = q1Topt, y = minLife, xend = q3Topt, yend = minLife)) + #lower end
  geom_segment(aes(x = q1Topt, y = maxLife, xend = q3Topt, yend = maxLife)) + #upper end
  theme_classic() + 
  geom_point(aes(x = medianTopt.True.wb, y =  medianLife.True.wb), color = "black", show.legend = FALSE) + 
  #facet_wrap(dub.wb$Method[1:6], nrow = 2, scales = "free") + 
  #theme(legend.position = "none") + 
  labs(title =  "Boxplot of Topt and Lifetime", 
       x = "Topt", 
       y = "Lifetime")
ggsave("Topt_Life_WB.png", width = 8, height = 5)

```

```{r exp.topt.maxlife.med}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND EXP DATA EXP MODEL
ind.exp.med <- function(x){
  (exp(median(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 2]))))
}

# MEAN EXP DATA EXP MODEL
mean.exp.med <- function(x){
  (exp(median(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 2]))))
}

# INV EXP DATA EXP MODEL
inv.exp.med <- function(x){
  (exp(median(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 2]))))
}

# MEAN INV EXP DATA EXP MODEL
mean.inv.exp.med <- function(x){
  (exp(median(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 2]))))
}

# INV MEAN EXP DATA EXP MODEL
inv.mean.exp.med <- function(x){
  (exp(median(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 2]))))
}

topt.mean.exp.med <- data.frame(
  Topt = c(optimize(ind.exp.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.exp.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.exp.med, interval = c( - 100, 200))$minimum, 
         optimize(mean.inv.exp.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.exp.med, interval = c( - 100, 200))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.exp.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.exp.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.exp.med, interval = c( - 100, 200))$objective, 
            1/optimize(mean.inv.exp.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.exp.med, interval = c( - 100, 200))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))
)

# Center point coordinates
center_x.exp.med <- topt.mean.exp.med$Topt[6]
center_y.exp.med <- topt.mean.exp.med$Lifetime[6]

# Plotting
ggplot(topt.mean.exp.med, aes(x = Topt, y = Lifetime, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.exp.med, y = center_y.exp.med, size = 3, col = viridis(6)[6], shape = 8)  + 
  labs(title = "Lifetime vs Topt (Posterior Median)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Topt", 
       y = "Lifetime")  + 
  theme_minimal() + 
  scale_color_manual(values = viridis(6)) + 
  coord_cartesian(xlim = c(center_x.exp.med - 0.5, center_x.exp.med + 0.5), ylim = c(center_y.exp.med - 3, center_y.exp.med + 3))

```

```{r WB.topt.maxlife.med}
# TRUE
f <- function(x, a = 0.001094, mu = 22.3, c = 0.066){
  a * (x - mu)^2 + c
}

# IND WB DATA EXP MODEL
ind.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 2])))
}

# MEAN WB DATA EXP MODEL
mean.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 2])))
}

# INV WB DATA EXP MODEL
inv.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 2])))
}

# MEAN INV WB DATA EXP MODEL
mean.inv.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 2])))
}

# INV MEAN WB DATA EXP MODEL
inv.mean.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 2])))
}

# IND WB DATA WB MODEL
ind.wb.wb.med <- function(x){
  exp(median(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 2])))) * (x - 
         median(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 2]))))^2  + 
         median(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 2])))
}

topt.mean.wb.med <- data.frame(
  Topt = c(optimize(ind.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(mean.inv.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(inv.mean.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(ind.wb.wb.med, interval = c(min(xseq), max(xseq)))$minimum, 
         optimize(f, interval = c(min(xseq), max(xseq)))$minimum), 
  Lifetime = c(1/optimize(ind.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(mean.inv.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(inv.mean.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(ind.wb.wb.med, interval = c(min(xseq), max(xseq)))$objective, 
            1/optimize(f, interval = c(min(xseq), max(xseq)))$objective
            ), 
  Method = factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"), levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))
)

# Center point coordinates
center_x.wb.med <- topt.mean.wb.med$Topt[7]
center_y.wb.med <- topt.mean.wb.med$Lifetime[7]

# Plotting
ggplot(topt.mean.wb.med, aes(x = Topt, y = Lifetime, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.wb.med, y = center_y.wb.med, size = 3, col = plasma(7)[7], shape = 8)  + 
  labs(title = "Lifetime vs Topt (Posterior Median)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Topt", 
       y = "Lifetime")  + 
  theme_minimal() + 
  scale_color_manual(values = plasma(7)) + 
  coord_cartesian(xlim = c(center_x.wb.med - 1, center_x.wb.med + 1), ylim = c(center_y.wb.med - 3, center_y.wb.med + 3))
```



```{r exp.extreme.mean}
solve_quadratic.mean <- function(f) {
  # Calculate discriminant
  a <- exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- - 2 * 
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) * 
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- mean(unlist(lapply(f[[3]], function(matrix) matrix[, 1])))  + 
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) * 
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >=  0) {
    x1 <- ( - b + sqrt(discriminant)) / (2 * a)
    x2 <- ( - b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.df.mean <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve")), 
  Low = c(solve_quadratic.mean(param_list1)[2], 
        solve_quadratic.mean(param_list2)[2], 
        solve_quadratic.mean(param_list3)[2], 
        solve_quadratic.mean(param_list4)[2], 
        solve_quadratic.mean(param_list5)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.mean(param_list1)[1], 
         solve_quadratic.mean(param_list2)[1], 
         solve_quadratic.mean(param_list3)[1], 
         solve_quadratic.mean(param_list4)[1], 
         solve_quadratic.mean(param_list5)[1], 
         51.542)
)

center_x.exp.extreme <- ext.df.mean$Low[6]
center_y.exp.extreme <- ext.df.mean$High[6]

# Plotting
ggplot(ext.df.mean, aes(x = Low, y = High, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.exp.extreme, y = center_y.exp.extreme, size = 3, col =  viridis(6)[6], shape = 8)  + 
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day (Posterior Mean)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Low", 
       y = "High")  + 
  theme_minimal() + 
  scale_color_manual(values = viridis(6)) + 
  coord_cartesian(xlim = c(center_x.exp.extreme - 7, center_x.exp.extreme + 7), ylim = c(center_y.exp.extreme - 50, center_y.exp.extreme + 50))

```

```{r exp.extreme.boxplot}

df_list <- list(df.new1, df.new2, df.new3, df.new4, df.new5)

# Lists to store results
x_values_list <- list()

# Loop through dataframes
for (df_index in 1:length(df_list)) {
  df <- df_list[[df_index]]
  x_values <- numeric()
  
  if (df_index  ==  1 || df_index  ==  2) {
    a_col <- 3
    b_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    b_col <- 5
    c_col <- 1
  }
  
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    b <- - 2 * (df[i, b_col]) * exp(df[i, a_col])
    c <- df[i, c_col] + exp(df[i, a_col]) * (df[i, b_col])^2
    
    # Solve quadratic equation for x when y = 1
    discriminant <- b^2 - 4 * a * (c - 1)
    if (discriminant >=  0) {
      x1 <- ( - b + sqrt(discriminant)) / (2 * a)
      x2 <- ( - b - sqrt(discriminant)) / (2 * a)
      x_values <- c(x_values, x1, x2)  
    } else {
      # If discriminant < 0, no real solutions
      warning("No real solutions for y = 1 in quadratic equation.")
    }
  }
  x_values_list[[length(x_values_list) + 1]] <- x_values  
}

double.box.df.ex <- data.frame(Low = numeric(), High = numeric())

# Loop through the list
for (i in seq_along(x_values_list)) {
  # Extract values from the list
  x_values <- x_values_list[[i]]
  
  # Create a dataframe with even indices as "low" and odd indices as "high"
  temp_df <- data.frame(High = x_values[c(TRUE, FALSE)], Low = x_values[c(FALSE, TRUE)])
  
  # Bind the dataframe to the result dataframe
  double.box.df.ex <- rbind(double.box.df.ex, temp_df)
}
double.box.df.ex <- rbind(double.box.df.ex, data.frame(Low = -6.935, 	 High = 51.542))

double.box.df.ex$Method <- factor(c(rep("Individual Exp Data, Exp Model", 938), rep("Mean Exp Data, Exp Model", 938), rep("Individual Inverse Exp Data, Trunc Norm Model", 938), 
               rep("Mean Inverse Exp Data, Trunc Norm Model", 938), rep("Inverse Mean Exp Data, Trunc Norm Model", 938) , "True Curve")
)



plot.x.ex <- ggplot(double.box.df.ex, aes(x =  Method, y =  Low)) + 
  geom_boxplot()
plot.x.ex <- layer_data(plot.x.ex)[, 1:6]

plot.y.ex <- ggplot(double.box.df.ex, aes(x =  Method, y =  High)) + 
  geom_boxplot() 
plot.y.ex <- layer_data(plot.y.ex)[, 1:6]

dub.ex <- double.box.df.ex |> group_by(Method) |> summarise(medianLow = median(Low), 
                                                     medianHigh = median(High), 
                                                     q1Low = quantile(Low, probs = 0.25), 
                                                     q3Low = quantile(Low, probs = 0.75), 
                                                     q1High = quantile(High, probs = 0.25), 
                                                     q3High = quantile(High, probs = 0.75)) |> 
  mutate(iqrLow = q3Low - q1Low, 
         iqrHigh = q3High - q1High, 
         maxLow = q3Low + 1.5 * iqrLow, 
         minLow = q1Low - 1.5 * iqrLow, 
         maxHigh = q3High + 1.5 * iqrHigh, 
         minHigh = q3High - 1.5 * iqrHigh, 
         Middle.Low = plot.x.ex$middle, 
         Middle.High = plot.y.ex$middle)

dub.ex$Method <- factor(dub.ex$Method, levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

medianLow.True.ex <- as.numeric(rep(dub.ex[6, 2], 5))
medianHigh.True.ex <- as.numeric(rep(dub.ex[6, 3], 5))

colnames(plot.x.ex) <- paste0("x.", gsub("y", "", colnames(plot.x.ex)))
colnames(plot.y.ex) <- paste0("y.", gsub("y", "", colnames(plot.y.ex)))
df.ex <- cbind(plot.x.ex, plot.y.ex)
df.ex$Method <- factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"))

ggplot(data = dub.ex[1:5, ], aes(fill = Method, color = Method))  + 
  scale_fill_manual(values = viridis(5)) + 
  scale_color_manual(values = viridis(5)) + 
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), 
            color = "black", fill = NA)  +
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), alpha = 0.3)  + 
  geom_segment(aes(x = minLow, y = plot.y.ex$y.middle[1:5], xend = maxLow, yend = plot.y.ex$y.middle[1:5])) + #whiskers
  geom_segment(aes(x = minLow, y = q1High, xend = minLow, yend = q3High)) + #lower end
  geom_segment(aes(x = maxLow, y = q1High, xend = maxLow, yend = q3High)) + #upper end
  geom_segment(aes(x = plot.x.ex$x.middle[1:5], y = minHigh, xend = plot.x.ex$x.middle[1:5], yend = maxHigh)) + #whiskers
  geom_segment(aes(x = q1Low, y = minHigh, xend = q3Low, yend = minHigh)) + #lower end
  geom_segment(aes(x = q1Low, y = maxHigh, xend = q3Low, yend = maxHigh)) + #upper end
  theme_classic() + 
  #facet_wrap(dub.ex$Method[1:5], nrow = 2, scales = "free") + 
  geom_point(aes(x = medianLow.True.ex, y =  medianHigh.True.ex), color = "black", show.legend = FALSE) + 
  #theme(legend.position = "none") + 
  labs(title =  "Boxplot of Extreme Temperatures", 
       x = "Low", 
       y = "High")
ggsave("Ex_Temp_Exp.png", width = 8, height = 5)
```

```{r WB.extreme.mean}

solve_quadratic.mean.wb <- function(f) {
  # Calculate discriminant
  a <- exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- - 2 * 
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) * 
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- mean(unlist(lapply(f[[3]], function(matrix) matrix[, 1])))  + 
    exp(mean(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) * 
    mean(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >=  0) {
    x1 <- ( - b + sqrt(discriminant)) / (2 * a)
    x2 <- ( - b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.df.mean.wb <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve")), 
  Low = c(solve_quadratic.mean.wb(Weibull_param_list1)[2], 
        solve_quadratic.mean.wb(Weibull_param_list2)[2], 
        solve_quadratic.mean.wb(Weibull_param_list3)[2], 
        solve_quadratic.mean.wb(Weibull_param_list4)[2], 
        solve_quadratic.mean.wb(Weibull_param_list5)[2], 
        solve_quadratic.mean.wb(Weibull_param_list6)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.mean.wb(Weibull_param_list1)[1], 
         solve_quadratic.mean.wb(Weibull_param_list2)[1], 
         solve_quadratic.mean.wb(Weibull_param_list3)[1], 
         solve_quadratic.mean.wb(Weibull_param_list4)[1], 
         solve_quadratic.mean.wb(Weibull_param_list5)[1], 
         solve_quadratic.mean.wb(Weibull_param_list6)[1], 
         51.542)
)

center_x.wb.extreme <- ext.df.mean.wb$Low[7]
center_y.wb.extreme <- ext.df.mean.wb$High[7]

# Plotting
ggplot(ext.df.mean.wb, aes(x = Low, y = High, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.wb.extreme, y = center_y.wb.extreme, size = 3, col = plasma(7)[7], shape = 8)  + 
  scale_color_manual(values = plasma(7)) + 
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day (Posterior Mean)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Low", 
       y = "High")  + 
  theme_minimal() + 
  coord_cartesian(xlim = c(center_x.wb.extreme - 3, center_x.wb.extreme + 3), ylim = c(center_y.wb.extreme - 3, center_y.wb.extreme + 3))

```

```{r WB.extreme.boxplot}

df_list.wb <- list(df.new1_W, df.new2_W, df.new3_W, df.new4_W, df.new5_W, df.new6_W)

# Lists to store results
x_values_list.wb <- list()
    
# Loop through dataframes
for (df_index.wb in 1:length(df_list.wb)) {
  df <- df_list.wb[[df_index.wb]]
  x_values.wb <- numeric()
  
  if (df_index.wb  ==  1 || df_index.wb  ==  2) {
    a_col <- 3
    b_col <- 4
    c_col <- 1
  } else {
    a_col <- 3
    b_col <- 5
    c_col <- 1
  }
  
  for (i in 1:nrow(df)) {
    a <- exp(df[i, a_col])
    b <- - 2 * (df[i, b_col]) * exp(df[i, a_col])
    c <- df[i, c_col] + exp(df[i, a_col]) * (df[i, b_col])^2
    
    # Solve quadratic equation for x when y = 1
    discriminant.wb <- b^2 - 4 * a * (c - 1)
    if (discriminant.wb >=  0) {
      x1.wb <- ( - b + sqrt(discriminant.wb)) / (2 * a)
      x2.wb <- ( - b - sqrt(discriminant.wb)) / (2 * a)
      x_values.wb <- c(x_values.wb, x1.wb, x2.wb)  
    } else {
      # If discriminant < 0, no real solutions
      warning("No real solutions for y = 1 in quadratic equation.")
    }
  }
  x_values_list.wb[[length(x_values_list.wb) + 1]] <- x_values.wb  
}

double.box.df.ex.wb <- data.frame(Low = numeric(), High = numeric())

# Loop through the list
for (i in seq_along(x_values_list.wb)) {
  # Extract values from the list
  x_values.wb <- x_values_list.wb[[i]]
  
  # Create a dataframe with even indices as "low" and odd indices as "high"
  temp_df.wb <- data.frame(High = x_values.wb[c(TRUE, FALSE)], Low = x_values.wb[c(FALSE, TRUE)])
  
  # Bind the dataframe to the result dataframe
  double.box.df.ex.wb <- rbind(double.box.df.ex.wb, temp_df.wb)
}
double.box.df.ex.wb <- rbind(double.box.df.ex.wb, data.frame(Low = -6.935, 	 High = 51.542))

double.box.df.ex.wb$Method <- factor(c(rep("Individual WB Data, Exp Model", 938), rep("Mean WB Data, Exp Model", 938), rep("Individual Inverse WB Data, Trunc Norm Model", 938), 
               rep("Mean Inverse WB Data, Trunc Norm Model", 938), rep("Inverse Mean WB Data, Trunc Norm Model", 938), rep("WB Data, WB Model", 938), "True Curve" 
               ), 
               levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve")
)



plot.x.ex.wb <- ggplot(double.box.df.ex.wb, aes(x =  Method, y =  Low)) + 
  geom_boxplot()
plot.x.ex.wb <- layer_data(plot.x.ex.wb)[, 1:18]

plot.y.ex.wb <- ggplot(double.box.df.ex.wb, aes(x =  Method, y =  High)) + 
  geom_boxplot() 
plot.y.ex.wb <- layer_data(plot.y.ex.wb)[, 1:18]

dub.ex.wb <- double.box.df.ex.wb |> group_by(Method) |> summarise(medianLow = median(Low), 
                                                     medianHigh = median(High), 
                                                     q1Low = quantile(Low, probs = 0.25), 
                                                     q3Low = quantile(Low, probs = 0.75), 
                                                     q1High = quantile(High, probs = 0.25), 
                                                     q3High = quantile(High, probs = 0.75)) |> 
  mutate(iqrLow = q3Low - q1Low, 
         iqrHigh = q3High - q1High, 
         maxLow = q3Low + 1.5 * iqrLow, 
         minLow = q1Low - 1.5 * iqrLow, 
         maxHigh = q3High + 1.5 * iqrHigh, 
         minHigh = q3High - 1.5 * iqrHigh, 
         Middle.Low = plot.x.ex.wb$middle, 
         Middle.High = plot.y.ex.wb$middle)

dub.ex.wb$Method <- factor(dub.ex.wb$Method, levels = c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))

medianLow.True.ex.wb <- as.numeric(rep(dub.ex.wb[7, 2], 6))
medianHigh.True.ex.wb <- as.numeric(rep(dub.ex.wb[7, 3], 6))

colnames(plot.x.ex.wb) <- paste0("x.", gsub("y", "", colnames(plot.x.ex.wb)))
colnames(plot.y.ex.wb) <- paste0("y.", gsub("y", "", colnames(plot.y.ex.wb)))
df.ex.wb <- cbind(plot.x.ex.wb, plot.y.ex.wb)
df.ex.wb$Method <- factor(c("Individual WB Data, Exp Model", "Mean WB Data, Exp Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", "Inverse Mean WB Data, Trunc Norm Model", "WB Data, WB Model", "True Curve"))

ggplot(data = dub.ex.wb[1:6, ], aes(fill = Method, color = Method))  + 
  scale_fill_manual(values = plasma(6)) + 
  scale_color_manual(values = plasma(6)) + 
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), 
            color = "black", fill = NA)  + 
  geom_rect(aes(xmin = q1Low, xmax = q3Low, ymin = q1High, ymax = q3High), alpha = 0.3)  + 
  geom_segment(aes(x = minLow, y = plot.y.ex.wb$y.middle[1:6], xend = maxLow, yend = plot.y.ex.wb$y.middle[1:6])) + #whiskers
  geom_segment(aes(x = minLow, y = q1High, xend = minLow, yend = q3High)) + #lower end
  geom_segment(aes(x = maxLow, y = q1High, xend = maxLow, yend = q3High)) + #upper end
  geom_segment(aes(x = plot.x.ex.wb$x.middle[1:6], y = minHigh, xend = plot.x.ex.wb$x.middle[1:6], yend = maxHigh)) + #whiskers
  geom_segment(aes(x = q1Low, y = minHigh, xend = q3Low, yend = minHigh)) + #lower end
  geom_segment(aes(x = q1Low, y = maxHigh, xend = q3Low, yend = maxHigh)) + #upper end
  theme_classic() + 
  #facet_wrap(dub.ex.wb$Method[1:6], nrow = 2) + 
  geom_point(aes(x = medianLow.True.ex.wb, y =  medianHigh.True.ex.wb), color = "black", show.legend = FALSE) + 
  #theme(legend.position = "none") + 
  labs(title =  "Boxplot of Extreme Temperatures", 
       x = "Low", 
       y = "High")
ggsave("Ex_Temp_WB.png", width = 8, height = 5)
```

```{r exp.extreme.med}
solve_quadratic.med <- function(f) {
  # Calculate discriminant
  a <- exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- - 2 * 
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) * 
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- median(unlist(lapply(f[[3]], function(matrix) matrix[, 1])))  + 
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) * 
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >=  0) {
    x1 <- ( - b + sqrt(discriminant)) / (2 * a)
    x2 <- ( - b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.df.med <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve"), levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "True Curve")), 
  Low = c(solve_quadratic.med(param_list1)[2], 
        solve_quadratic.med(param_list2)[2], 
        solve_quadratic.med(param_list3)[2], 
        solve_quadratic.med(param_list4)[2], 
        solve_quadratic.med(param_list5)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.med(param_list1)[1], 
         solve_quadratic.med(param_list2)[1], 
         solve_quadratic.med(param_list3)[1], 
         solve_quadratic.med(param_list4)[1], 
         solve_quadratic.med(param_list5)[1], 
         51.542)
)

center_x.exp.extreme.med <- ext.df.med$Low[6]
center_y.exp.extreme.med <- ext.df.med$High[6]

# Plotting
ggplot(ext.df.med, aes(x = Low, y = High, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.exp.extreme.med, y = center_y.exp.extreme.med, size = 3, col =  viridis(6)[6], shape = 8)  + 
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day (Posterior Median)", 
       subtitle = "Data Generated from Exponential Distribution", 
       x = "Low", 
       y = "High")  + 
  theme_minimal() + 
  scale_color_manual(values = viridis(6)) + 
  coord_cartesian(xlim = c(center_x.exp.extreme.med - 5, center_x.exp.extreme.med + 5), ylim = c(center_y.exp.extreme.med - 50, center_y.exp.extreme.med + 50))

```

```{r WB.extreme.med}
solve_quadratic.med.wb <- function(f) {
  # Calculate discriminant
  a <- exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  b <- - 2 * 
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1]))) * 
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1]))))
  c <- median(unlist(lapply(f[[3]], function(matrix) matrix[, 1])))  + 
    exp(median(unlist(lapply(f[[1]], function(matrix) matrix[, 1])))) * 
    median(unlist(lapply(f[[2]], function(matrix) matrix[, 1])))^2
  discriminant <- b^2 - 4 * a * (c - 1)
  
  # Solve quadratic equation
  if (discriminant >=  0) {
    x1 <- ( - b + sqrt(discriminant)) / (2 * a)
    x2 <- ( - b - sqrt(discriminant)) / (2 * a)
    return(c(x1, x2))
  } else {
    warning("No real solutions for y = 1 in quadratic equation.")
    return(NA)
  }
}

ext.df.med.wb <- data.frame(
  Method = factor(c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve"), 
               levels = c("Individual Exp Data, Exp Model", "Mean Exp Data, Exp Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", "Inverse Mean Exp Data, Trunc Norm Model", "Individual WB Data, WB Model", "True Curve")), 
  Low = c(solve_quadratic.med.wb(Weibull_param_list1)[2], 
        solve_quadratic.med.wb(Weibull_param_list2)[2], 
        solve_quadratic.med.wb(Weibull_param_list3)[2], 
        solve_quadratic.med.wb(Weibull_param_list4)[2], 
        solve_quadratic.med.wb(Weibull_param_list5)[2], 
        solve_quadratic.med.wb(Weibull_param_list6)[2], 
        -6.935
        ), 
  High = c(solve_quadratic.med.wb(Weibull_param_list1)[1], 
         solve_quadratic.med.wb(Weibull_param_list2)[1], 
         solve_quadratic.med.wb(Weibull_param_list3)[1], 
         solve_quadratic.med.wb(Weibull_param_list4)[1], 
         solve_quadratic.med.wb(Weibull_param_list5)[1], 
         solve_quadratic.med.wb(Weibull_param_list6)[1], 
         51.542)
)

center_x.wb.extreme.med <- ext.df.med.wb$Low[7]
center_y.wb.extreme.med <- ext.df.med.wb$High[7]

# Plotting
ggplot(ext.df.med.wb, aes(x = Low, y = High, color = Method))  + 
  geom_point()  + 
  geom_point(x = center_x.wb.extreme.med, y = center_y.wb.extreme.med, size = 3, col = plasma(7)[7], shape = 8)  + 
  labs(title = "Temperatures where Predicted Lifetime Hits 1 Day (Posterior Median)", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Low", 
       y = "High")  + 
  scale_color_manual(values = plasma(7)) + 
  theme_minimal() + 
  coord_cartesian(xlim = c(center_x.wb.extreme.med - 3, center_x.wb.extreme.med + 3), ylim = c(center_y.wb.extreme.med - 3, center_y.wb.extreme.med + 3))

```



```{r QQPlot.Ind.Exp.Data}
ind.exp.10 <- qqPlot(data.list[[100]]$trait[data.list[[100]]$T == 10], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.exp.17 <- qqPlot(data.list[[100]]$trait[data.list[[100]]$T == 17], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.exp.21 <- qqPlot(data.list[[100]]$trait[data.list[[100]]$T == 21], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.exp.25 <- qqPlot(data.list[[100]]$trait[data.list[[100]]$T == 25], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.exp.32 <- qqPlot(data.list[[100]]$trait[data.list[[100]]$T == 32], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)
png(file="ind.exp.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(ind.exp.10, pch = 20, xlim = c(0, 80), ylim = c(0, 100), col = viridis(5)[1], 
     main = "QQ - Plot for Exp Data and Exp Distribution", 
       xlab = "Quantiles of Exponential with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(ind.exp.17, pch = 20, col =  viridis(5)[2])
points(ind.exp.21, pch = 20, col =  viridis(5)[3])
points(ind.exp.25, pch = 20, col =  viridis(5)[4])
points(ind.exp.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Mean.Exp.Data}
group_means.mean.exp <- tapply(data.list[[100]]$trait, data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.exp <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.exp)  # Extract means and unlist the result
    )

mean.exp.10 <- qqPlot(df.mean.mean.exp$trait[df.mean.mean.exp$T == 10], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.exp.17 <- qqPlot(df.mean.mean.exp$trait[df.mean.mean.exp$T == 17], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.exp.21 <- qqPlot(df.mean.mean.exp$trait[df.mean.mean.exp$T == 21], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.exp.25 <- qqPlot(df.mean.mean.exp$trait[df.mean.mean.exp$T == 25], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.exp.32 <- qqPlot(df.mean.mean.exp$trait[df.mean.mean.exp$T == 32], 
       distribution = "exp", 
       param.list = list(rate = (exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

png(file="mean.exp.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.exp.10, pch = 20, xlim = c(0, 30), ylim = c(0, 50), col = viridis(5)[1], 
     main = "QQ - Plot for Mean Exp Data and Exp Distribution", 
       xlab = "Quantiles of Exponential with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.exp.17, pch = 20, col =  viridis(5)[2])
points(mean.exp.21, pch = 20, col =  viridis(5)[3])
points(mean.exp.25, pch = 20, col =  viridis(5)[4])
points(mean.exp.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.Exp.Data}
inv.exp.10 <- qqPlot(1/data.list[[100]]$trait[data.list[[100]]$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.exp.17 <- qqPlot(1/data.list[[100]]$trait[data.list[[100]]$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.exp.21 <- qqPlot(1/data.list[[100]]$trait[data.list[[100]]$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.exp.25 <- qqPlot(1/data.list[[100]]$trait[data.list[[100]]$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.exp.32 <- qqPlot(1/data.list[[100]]$trait[data.list[[100]]$T == 32], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="inv.exp.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.exp.10, pch = 20, col = viridis(5)[1], 
     main = "QQ - Plot for Inverse Exp Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.exp.17, pch = 20, col =  viridis(5)[2])
points(inv.exp.21, pch = 20, col =  viridis(5)[3])
points(inv.exp.25, pch = 20, col =  viridis(5)[4])
points(inv.exp.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Mean.Inv.Exp.Data}
group_means.mean.exp <- tapply(data.list[[100]]$trait, data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.exp <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.exp)  # Extract means and unlist the result
    )

mean.inv.exp.10 <- qqPlot(1/df.mean.mean.exp$trait[df.mean.mean.exp$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.17 <- qqPlot(1/df.mean.mean.exp$trait[df.mean.mean.exp$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.21 <- qqPlot(1/df.mean.mean.exp$trait[df.mean.mean.exp$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.25 <- qqPlot(1/df.mean.mean.exp$trait[df.mean.mean.exp$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.exp.32 <- qqPlot(1/df.mean.mean.exp$trait[df.mean.mean.exp$T == 32], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="mean.inv.exp.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.inv.exp.10, pch = 20, xlim = c(0, 30), ylim = c(0, 0.75), col = viridis(5)[1], 
     main = "QQ - Plot for Mean Inverse Exp Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.inv.exp.17, pch = 20, col =  viridis(5)[2])
points(mean.inv.exp.21, pch = 20, col =  viridis(5)[3])
points(mean.inv.exp.25, pch = 20, col =  viridis(5)[4])
points(mean.inv.exp.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.Mean.Exp.Data}
group_means.inv.exp <- tapply(1/data.list[[100]]$trait, data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.inv.exp <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.inv.exp)  # Extract means and unlist the result
    )

inv.mean.exp.10 <- qqPlot(df.mean.inv.exp$trait[df.mean.inv.exp$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.17 <- qqPlot(df.mean.inv.exp$trait[df.mean.inv.exp$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.21 <- qqPlot(df.mean.inv.exp$trait[df.mean.inv.exp$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.25 <- qqPlot(df.mean.inv.exp$trait[df.mean.inv.exp$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.exp.32 <- qqPlot(df.mean.inv.exp$trait[df.mean.inv.exp$T == 32], 
       distribution = "normTrunc", 
       param.list = list(mean = (exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2  + 
                               mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="inv.mean.exp.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.mean.exp.10, pch = 20, xlim = c(0, 1), ylim = c(0, 5), col = viridis(5)[1], 
     main = "QQ - Plot for Inverse Mean Exp Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.mean.exp.17, pch = 20, col =  viridis(5)[2])
points(inv.mean.exp.21, pch = 20, col =  viridis(5)[3])
points(inv.mean.exp.25, pch = 20, col =  viridis(5)[4])
points(inv.mean.exp.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```



```{r QQPlot.Ind.WB.Data}
ind.wb.10 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 10], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.wb.17 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 17], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.wb.21 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 21], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.wb.25 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 25], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

ind.wb.32 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 32], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

png(file="ind.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(ind.wb.10, xlim = c(0, 6), ylim = c(0, 35), pch = 20, col = viridis(5)[1], 
       main = "QQ - Plot for WB Data and Exp Distribution", 
       xlab = "Quantiles of Exponential with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(ind.wb.17, pch = 20, col =  viridis(5)[2])
points(ind.wb.21, pch = 20, col =  viridis(5)[3])
points(ind.wb.25, pch = 20, col =  viridis(5)[4])
points(ind.wb.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Mean.WB.Data}
group_means.mean.wb <- tapply(Weibull_data.list[[100]]$trait, Weibull_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.wb <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.wb)  # Extract means and unlist the result
    )

mean.wb.10 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 10], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.wb.17 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 17], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.wb.21 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 21], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.wb.25 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 25], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)

mean.wb.32 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 32], 
       distribution = "exp", 
       param.list = list(rate = exp(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))), plot.it = FALSE)


png(file="mean.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.wb.10, pch = 20, xlim = c(0, 3), ylim = c(0, 30), col = viridis(5)[1], 
     main = "QQ - Plot for Mean WB Data and Exp Distribution", 
       xlab = "Quantiles of Exponential with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.wb.17, pch = 20, col = viridis(5)[2])
points(mean.wb.21, pch = 20, col =  viridis(5)[3])
points(mean.wb.25, pch = 20, col =  viridis(5)[4])
points(mean.wb.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```

```{r QQPlot.Inv.WB.Data}
inv.wb.10 <- qqPlot(1/Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.17 <- qqPlot(1/Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.21 <- qqPlot(1/Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.25 <- qqPlot(1/Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.wb.32 <- qqPlot(1/Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 32], 
       distribution = "normTrunc", 
        param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list3[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="inv.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.wb.10, xlim = c(0, 30), ylim = c(0, 3), pch = 20, col = viridis(5)[1], 
       main = "QQ - Plot for Inverse WB Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.wb.17, pch = 20, col = viridis(5)[2])
points(inv.wb.21, pch = 20, col = viridis(5)[3])
points(inv.wb.25, pch = 20, col =  viridis(5)[4])
points(inv.wb.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.Mean.Inv.WB.Data}
group_means.mean.wb <- tapply(Weibull_data.list[[100]]$trait, Weibull_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.mean.wb <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.mean.wb)  # Extract means and unlist the result
    )

mean.inv.wb.10 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.17 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.21 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.25 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

mean.inv.wb.32 <- qqPlot(df.mean.mean.wb$trait[df.mean.mean.wb$T == 32], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list4[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="mean.inv.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(mean.inv.wb.10, pch = 20, ylim = c(0, 30), xlim = c(0, 150), col = viridis(5)[1], 
       main = "QQ - Plot for Mean Inverse WB Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(mean.inv.wb.17, pch = 20, col =  viridis(5)[2])
points(mean.inv.wb.21, pch = 20, col =  viridis(5)[3])
points(mean.inv.wb.25, pch = 20, col =  viridis(5)[4])
points(mean.inv.wb.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.Inv.Mean.WB.Data}
group_means.inv.wb <- tapply(1/Weibull_data.list[[100]]$trait, Weibull_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.inv.wb <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.inv.wb)  # Extract means and unlist the result
    )

inv.mean.wb.10 <- qqPlot(df.mean.inv.wb$trait[df.mean.inv.wb$T == 10], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.17 <- qqPlot(df.mean.inv.wb$trait[df.mean.inv.wb$T == 17], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.21 <- qqPlot(df.mean.inv.wb$trait[df.mean.inv.wb$T == 21], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.25 <- qqPlot(df.mean.inv.wb$trait[df.mean.inv.wb$T == 25], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

inv.mean.wb.32 <- qqPlot(df.mean.inv.wb$trait[df.mean.inv.wb$T == 32], 
       distribution = "normTrunc", 
       param.list = list(mean = exp(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1])))), 
                       sd = 1/mean(unlist(lapply(Weibull_param_list5[[5]], function(matrix) matrix[, 1]))), 
                       min = 0, 
                       max = Inf), 
       plot.it = FALSE)

png(file="inv.mean.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(inv.mean.wb.10, pch = 20, xlim = c(0, 60), ylim = c(0, 1), col = viridis(5)[1], 
       main = "QQ - Plot for Inverse Mean WB Data and Trunc Norm Distribution", 
       xlab = "Quantiles of Truncated Normal with Posterior Mean Rate Parameter", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(inv.mean.wb.17, pch = 20, col =  viridis(5)[2])
points(inv.mean.wb.21, pch = 20, col =  viridis(5)[3])
points(inv.mean.wb.25, pch = 20, col =  viridis(5)[4])
points(inv.mean.wb.32, pch = 20, col =  viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()

```

```{r QQPlot.WB.Data.WB.Model}
wb.wb.10 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 10], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (10 - 
                               (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))/log(2)^(1/mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), 
                         shape = mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), plot.it = FALSE)

wb.wb.17 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 17], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (17 - 
                               (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))/log(2)^(1/mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), 
                         shape = mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), plot.it = FALSE)

wb.wb.21 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 21], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (21 - 
                               (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))/log(2)^(1/mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))),
                         shape = mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), plot.it = FALSE)

wb.wb.25 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 25], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (25 - 
                               (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))/log(2)^(1/mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), 
                         shape = mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), plot.it = FALSE)

wb.wb.32 <- qqPlot(Weibull_data.list[[100]]$trait[Weibull_data.list[[100]]$T == 32], 
       distribution = "weibull", 
       param.list = list(scale = 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (32 - 
                               (mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1])))))^2  + 
                               mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))/log(2)^(1/mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), 
                         shape = mean(unlist(lapply(Weibull_param_list6[[5]], function(matrix) matrix[, 1])))), plot.it = FALSE)


png(file="ind.wb.wb.qq.png",
    width = 7, height = 6, units = "in", res = 250)
plot(wb.wb.10, xlim = c(0, 40), ylim = c(0, 35), pch = 20, col = viridis(5)[1], 
       main = "QQ - Plot for WB Data and WB Distribution", 
       xlab = "Quantiles of Weibull with Posterior Mean Parameters", 
       ylab = "Quantiles of Generated Data with True Parameters")
points(wb.wb.17, pch = 20, col = viridis(5)[2])
points(wb.wb.21, pch = 20, col = viridis(5)[3])
points(wb.wb.25, pch = 20, col = viridis(5)[4])
points(wb.wb.32, pch = 20, col = viridis(5)[5])
legend("topleft", legend = c("10", "17", "21", "25", "32"), 
       pch = c(20, 20, 20, 20, 20), col = c(viridis(5)[1], viridis(5)[2], viridis(5)[3], viridis(5)[4], viridis(5)[5]))
abline(a = 0, b = 1, lwd = 2, col = "black")
dev.off()
```



```{r RMSE.Boxplot.Exp}
xdf1$true.value <- rep(f(seq(from = 5, to = 37, length.out = 250)), 938)
xdf2$true.value <- rep(f(seq(from = 5, to = 37, length.out = 250)), 938)
xdf3$true.value <- rep(f(seq(from = 5, to = 37, length.out = 250)), 938)
xdf4$true.value <- rep(f(seq(from = 5, to = 37, length.out = 250)), 938)
xdf5$true.value <- rep(f(seq(from = 5, to = 37, length.out = 250)), 938)


rmse1 <- xdf1 |> group_by(point) |> summarize(rmse1 = sqrt(mean((trunc.inv - 1/true.value)^2))) |> select(rmse1)
rmse2 <- xdf2 |> group_by(point) |> summarize(rmse2 = sqrt(mean((trunc.inv - 1/true.value)^2)))|> select(rmse2)
rmse3 <- xdf3 |> group_by(point) |> summarize(rmse3 = sqrt(mean((trunc.inv - 1/true.value)^2)))|> select(rmse3)
rmse4 <- xdf4 |> group_by(point) |> summarize(rmse4 = sqrt(mean((trunc.inv - 1/true.value)^2)))|> select(rmse4)
rmse5 <- xdf5 |> group_by(point) |> summarize(rmse5 = sqrt(mean((trunc.inv - 1/true.value)^2)))|> select(rmse5)

boxplot.df <- data.frame(
  Method = factor(c(rep("Individual Exp Data, Exp Model", 250), rep("Mean Exp Data, Exp Model", 250), rep("Individual Inverse Exp Data, Trunc Norm Model", 250), rep("Mean Inverse Exp Data, Trunc Norm Model", 250), rep("Inverse Mean Exp Data, Trunc Norm Model", 250)), 
                  levels = rev(c("Inverse Mean Exp Data, Trunc Norm Model", "Mean Inverse Exp Data, Trunc Norm Model", "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Exp Data, Exp Model", "Individual Exp Data, Exp Model"))), 
  RMSE = c(rmse1$rmse1, 
         rmse2$rmse2, 
         rmse3$rmse3, 
         rmse4$rmse4, 
         rmse5$rmse5
  ), 
  Temperature = rep(seq(from = 5, to = 37, length.out = 250), 5)
)

ggplot(boxplot.df, aes(y = Method, x = RMSE, fill = Method)) + 
  geom_boxplot() + 
  scale_fill_manual(values = viridis(5))  + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(title = "Boxplot of RMSE Comparisons", 
       subtitle = "Data Generated from Exponential Distribution")
ggplot(boxplot.df, aes(y = RMSE, x = Temperature, col = Method)) + 
  geom_line() + 
  scale_color_manual(values = viridis(5))  + 
  theme_classic() + 
  labs(title = "Plot of RMSE Comparisons", 
       subtitle = "Data Generated from Exponential Distribution")
```

```{r RMSE.Boxplot.WB}
xdf1_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)
xdf2_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)
xdf3_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)
xdf4_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)
xdf5_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)
xdf6_W$true.value <- rep(my.med(seq(from = 5, to = 37, length.out = 250)), 938)


rmse1.wb <- xdf1_W |> group_by(point) |> summarize(rmse1.wb = sqrt(mean((trunc.inv - true.value)^2))) |> select(rmse1.wb)
rmse2.wb <- xdf2_W |> group_by(point) |> summarize(rmse2.wb = sqrt(mean((trunc.inv - true.value)^2)))|> select(rmse2.wb)
rmse3.wb <- xdf3_W |> group_by(point) |> summarize(rmse3.wb = sqrt(mean((trunc.inv - true.value)^2)))|> select(rmse3.wb)
rmse4.wb <- xdf4_W |> group_by(point) |> summarize(rmse4.wb = sqrt(mean((trunc.inv - true.value)^2)))|> select(rmse4.wb)
rmse5.wb <- xdf5_W |> group_by(point) |> summarize(rmse5.wb = sqrt(mean((trunc.inv - true.value)^2)))|> select(rmse5.wb)
rmse6.wb <- xdf6_W |> group_by(point) |> summarize(rmse6.wb = sqrt(mean((trunc.inv - true.value)^2)))|> select(rmse6.wb)


boxplot.df.wb <- data.frame(
  Method = factor(c(rep("Individual WB Data, Exp Model", 250), rep("Mean WB Data, Exp Model", 250), rep("Individual Inverse WB Data, Trunc Norm Model", 250), rep("Mean Inverse WB Data, Trunc Norm Model", 250), rep("Inverse Mean WB Data, Trunc Norm Model", 250), rep("WB Data, WB Model", 250)), 
                  levels = rev(c("WB Data, WB Model", "Inverse Mean WB Data, Trunc Norm Model", "Mean Inverse WB Data, Trunc Norm Model", "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean WB Data, Exp Model", "Individual WB Data, Exp Model"))), 
  RMSE = c(rmse1.wb$rmse1.wb, 
         rmse2.wb$rmse2.wb, 
         rmse3.wb$rmse3.wb, 
         rmse4.wb$rmse4.wb, 
         rmse5.wb$rmse5.wb, 
         rmse6.wb$rmse6.wb
  ), 
  Temperature = c(rep(seq(from = 5, to = 37, length.out = 250), 6))
)

ggplot(boxplot.df.wb, aes(y = Method, x = RMSE, fill = Method)) + 
  geom_boxplot() + 
  scale_fill_manual(values = viridis(6))  + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(title = "Boxplot of RMSE Comparisons", 
       subtitle = "Data Generated from Weibull Distribution")
ggplot(boxplot.df.wb, aes(y = RMSE, x = Temperature, col = Method)) + 
  geom_line() + 
  scale_color_manual(values = viridis(6))  + 
  theme_classic() + 
  #ylim(0, 0.2) + 
  labs(title = "Plot of RMSE Comparisons", 
       subtitle = "Data Generated from Weibull Distribution")

joint.box <- rbind(boxplot.df, boxplot.df.wb)
joint.box$Method <- factor(joint.box$Method, levels = rev(desired_order.compare))

ggplot(joint.box, aes(y = Method, x = RMSE, fill = Method)) + 
  geom_boxplot() + 
  scale_fill_manual(values = viridis(11))  + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(title = "Boxplot of RMSE Comparisons", 
       subtitle = "Data Generated from Weibull Distribution")

ggplot(joint.box, aes(y = RMSE, x = Temperature, col = Method)) + 
  geom_line() + 
  scale_color_manual(values = viridis(11))  + 
  theme_classic() + 
  labs(title = "Plot of RMSE Comparisons", 
       subtitle = "Data Generated from Weibull Distribution")

```

```{r RMSE.Table.Exp}
summary_list <- list(
  xdf1 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf2 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf3 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf4 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf5 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2)))
)


# Convert the list into a matrix
RMSE.tab.exp <- do.call(rbind, summary_list)

RMSE.tab.exp$Method <- factor(c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"), 
  levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"
))

RMSE.tab.exp
RMSE.tab.exp |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(RMSE.tab.exp$Method))) + 
  labs(title = "RMSE Boxplot", 
       subtitle = "Exponential Data") + 
  coord_flip() + 
  theme_classic()
```

```{r RMSE.Table.WB}
summary_list.wb <- list(
  xdf1_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2))), 
  xdf2_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2))), 
  xdf3_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2))), 
  xdf4_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2))), 
  xdf5_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2))), 
  xdf6_W |> summarize(RMSE = sqrt(mean((value - 1/true.value)^2)))
)

# Convert the list into a matrix
RMSE.tab.wb <- do.call(rbind, summary_list.wb)

RMSE.tab.wb$Method <- factor(c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "Individual WB Data, WB Model"
  ), 
  levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "Individual WB Data, WB Model"
  ))

RMSE.tab.wb

RMSE.tab.wb |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = mako(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(RMSE.tab.wb$Method))) + 
  labs(title = "RMSE Boxplot", 
       subtitle = "Weibull Data") + 
  coord_flip() + 
  theme_classic()
```

```{r RMSE.Table.Compare}
summary_list.compare <- list(
  xdf1 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf1_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf6_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf2 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf2_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf3 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf3_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf4 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf4_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2))), 
  xdf5 |> summarize(RMSE = sqrt(mean((trunc.inv - 1/true.value)^2))), 
  xdf5_W |> summarize(RMSE = sqrt(mean((trunc.inv - true.value)^2)))
)

# Convert the list into a matrix
RMSE.tab.compare <- do.call(rbind, summary_list.compare)

RMSE.tab.compare$Method <- factor(c(
  "Individual Exp Data, Exp Model", 
  "Individual WB Data, Exp Model", 
  "Individual WB Data, WB Model", 
  "Mean Exp Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model"
), 
  levels =  c(
  "Individual Exp Data, Exp Model", 
  "Individual WB Data, Exp Model", 
  "Individual WB Data, WB Model", 
  "Mean Exp Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model"
))

RMSE.tab.compare

RMSE.tab.compare$Set <- factor(c("Exponential", "Weibull", "Weibull", rep(c("Exponential", "Weibull"), 4)))

RMSE.tab.compare |> ggplot(aes(x = Method, y = RMSE, fill = Set)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black") + 
  scale_fill_manual(values = mako(2)) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(RMSE.tab.compare$Method))) + 
  labs(title = "RMSE Boxplot", 
       subtitle = "Weibull Data") + 
  coord_flip() + 
  theme_classic()

```

```{r RMSE.mean.param.curve}
exp.mean.param.curve.rmse <- data.frame(
  RMSE = 
    c(sqrt(mean((1/ind.exp(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.exp(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.exp(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.inv.exp(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.mean.exp(xseq) - 1/f(xseq))^2)))
)

exp.mean.param.curve.rmse$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

wb.mean.param.curve.rmse <- data.frame(
  RMSE = 
    c(sqrt(mean((1/ind.wb(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.wb(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.wb(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/mean.inv.wb(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/inv.mean.wb(xseq) - 1/f(xseq))^2)), 
  sqrt(mean((1/ind.wb.wb(xseq) - 1/f(xseq))^2)))
)

wb.mean.param.curve.rmse$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))

exp.mean.param.curve.rmse |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = plasma(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(exp.mean.param.curve.rmse$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Exponential Distribution") + 
  theme_minimal()

wb.mean.param.curve.rmse |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(wb.mean.param.curve.rmse$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution") + 
  theme_minimal()

rbind(exp.mean.param.curve.rmse, wb.mean.param.curve.rmse) |> ggplot(aes(x = reorder(Method, - RMSE), y = RMSE))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = mako(10)[5])  + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  #scale_x_discrete(limits = levels(rbind(exp.mean.param.curve.rmse, wb.mean.param.curve.rmse)$Method))  + 
  coord_flip()  + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Method")  + 
  theme_minimal()

```

```{r RMSE.mean.curve}
exp.mean.curve.rmse <- data.frame(
  RMSE = c(sqrt(mean((mean.xdf1$avg.value.inv - 1/mean.xdf1$true_curve)^2)), 
  sqrt(mean((mean.xdf2$avg.value.inv - 1/mean.xdf2$true_curve)^2)), 
  sqrt(mean((mean.xdf3$avg.value.inv - 1/mean.xdf3$true_curve)^2)), 
  sqrt(mean((mean.xdf4$avg.value.inv - 1/mean.xdf4$true_curve)^2)), 
  sqrt(mean((mean.xdf5$avg.value.inv - 1/mean.xdf5$true_curve)^2)))
)

exp.mean.curve.rmse$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

wb.mean.curve.rmse <- data.frame(
  RMSE = 
    c(sqrt(mean((mean.xdf1_W$avg.value.inv - log(2)/mean.xdf1_W$true_curve)^2)), 
  sqrt(mean((mean.xdf2_W$avg.value.inv - log(2)/mean.xdf2_W$true_curve)^2)), 
  sqrt(mean((mean.xdf3_W$avg.value.inv - 1/mean.xdf3_W$true_curve)^2)), 
  sqrt(mean((mean.xdf4_W$avg.value.inv - 1/mean.xdf4_W$true_curve)^2)), 
  sqrt(mean((mean.xdf5_W$avg.value.inv - 1/mean.xdf5_W$true_curve)^2)), 
  sqrt(mean((mean.xdf6_W$avg.value.inv - log(2)/mean.xdf6_W$true_curve)^2)))
  
)

wb.mean.curve.rmse$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))


exp.mean.curve.rmse |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = plasma(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(exp.mean.curve.rmse$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Exponential Distribution") + 
  theme_minimal()

wb.mean.curve.rmse |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(wb.mean.curve.rmse$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution") + 
  theme_minimal()

rbind(exp.mean.curve.rmse, wb.mean.curve.rmse) |> ggplot(aes(x = reorder(Method, - RMSE), y = RMSE))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = mako(10)[5])  + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  #scale_x_discrete(limits = levels(rbind(exp.mean.curve.rmse, wb.mean.curve.rmse)$Method))  + 
  coord_flip()  + 
  labs(title = "RMSE of True and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution", 
       x = "Method")  + 
  theme_minimal()

```

```{r RMSE.data.exp}
data.rmse.ind.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(param_list1[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(param_list1[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(param_list1[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.ind.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.ind.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.mean.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(param_list2[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(param_list2[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(param_list2[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.mean.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.mean.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.inv.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(param_list3[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(param_list3[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(param_list3[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.inv.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.inv.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.mean.inv.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(param_list4[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(param_list4[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(param_list4[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.mean.inv.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.mean.inv.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.inv.mean.exp <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(param_list5[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(param_list5[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(param_list5[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.inv.mean.exp <- bind_rows(data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.inv.mean.exp(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.exp <- as.data.frame(rbind(rmse.ind.exp, 
      rmse.mean.exp, 
      rmse.inv.exp, 
      rmse.mean.inv.exp, 
      rmse.inv.mean.exp))
data.rmse.exp$Method <- factor(c("Individual Exp Data, Exp Model", 
                                 "Mean Exp Data, Exp Model", 
                                 "Individual Inverse Exp Data, Trunc Norm Model", 
               "Mean Inverse Exp Data, Trunc Norm Model", 
               "Inverse Mean Exp Data, Trunc Norm Model"), 
               levels = c(
  "Individual Exp Data, Exp Model", 
  "Mean Exp Data, Exp Model", 
  "Individual Inverse Exp Data, Trunc Norm Model", 
  "Mean Inverse Exp Data, Trunc Norm Model", 
  "Inverse Mean Exp Data, Trunc Norm Model"))

data.rmse.exp |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(data.rmse.exp$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of Data and Posterior Mean Curve", 
       subtitle = "Data Generated from an Exponential Distribution") + 
  theme_minimal()
```

```{r RMSE.data.wb}
data.rmse.ind.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list1[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list1[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list1[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.ind.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.ind.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.mean.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list2[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list2[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list2[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.mean.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.mean.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.inv.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list3[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list3[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list3[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.inv.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.inv.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.mean.inv.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list4[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list4[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list4[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.mean.inv.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.mean.inv.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.inv.mean.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list5[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list5[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list5[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.inv.mean.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.inv.mean.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.wb.wb <- function(temp, values, a, Topt, c) {
  curve_value <- 1/(exp(mean(unlist(lapply(Weibull_param_list6[[1]], function(matrix) matrix[, 1])))) * (temp - 
    mean(unlist(lapply(Weibull_param_list6[[2]], function(matrix) matrix[, 1]))))^2 + 
    mean(unlist(lapply(Weibull_param_list6[[3]], function(matrix) matrix[, 1]))))
  sqrt(mean((values - curve_value)^2))
}
# Group data by temperature and calculate RMSE for each group
rmse.wb.wb <- bind_rows(Weibull_data.list) %>%
  group_by(T) %>%
  summarise(
    rmse = data.rmse.wb.wb(unique(T), trait, a, Topt, c)) |> 
    summarise(
    RMSE = sqrt(mean(rmse^2))
  )

data.rmse.wb <- as.data.frame(rbind(rmse.ind.wb, 
      rmse.mean.wb, 
      rmse.inv.wb, 
      rmse.mean.inv.wb, 
      rmse.inv.mean.wb, 
      rmse.wb.wb))
data.rmse.wb$Method <- factor(c("Individual WB Data, Exp Model", 
                                 "Mean WB Data, Exp Model", 
                                 "Individual Inverse WB Data, Trunc Norm Model", 
               "Mean Inverse WB Data, Trunc Norm Model", 
               "Inverse Mean WB Data, Trunc Norm Model", 
               "WB Data, WB Model"), 
               levels = c(
  "Individual WB Data, Exp Model", 
  "Mean WB Data, Exp Model", 
  "Individual Inverse WB Data, Trunc Norm Model", 
  "Mean Inverse WB Data, Trunc Norm Model", 
  "Inverse Mean WB Data, Trunc Norm Model", 
  "WB Data, WB Model"))

data.rmse.wb |> ggplot(aes(x = Method, y = RMSE)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", fill = viridis(10)[5]) + 
  geom_text(aes(label = round(RMSE, 4)), hjust = - 0.2, position = position_dodge(width = 0.9))  + 
  scale_x_discrete(limits = rev(levels(data.rmse.wb$Method))) + 
  coord_flip() + 
  labs(title = "RMSE of Data and Posterior Mean Curve", 
       subtitle = "Data Generated from Weibull Distribution") + 
  theme_minimal()
```



```{r n.w.compare.exp.mr}
exp.ind.mr <- ggplot()  + 
  geom_line(data = N_mean.xdf1, aes(x = point, y = med.value), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf1, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf1, aes(x = point, y = med.value), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf1, aes(x = point, y = true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Individual Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("exp.ind.mr.png", plot = exp.ind.mr, height = 5, width = 6)

exp.mean.mr <- ggplot()  + 
  geom_line(data = N_mean.xdf2, aes(x = point, y = med.value), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf2, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf2, aes(x = point, y = med.value), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf2, aes(x = point, y = true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Mean Data)", 
       x = "Temperature", 
       y = "Mortality Rate") + 
  theme_minimal()
ggsave("exp.mean.mr.png", plot = exp.mean.mr, height = 5, width = 6)

exp.inv.mr <- ggplot()  + 
  geom_line(data = N_mean.xdf3, aes(x = point, y = med.value), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf3, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf3, aes(x = point, y = med.value), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf3, aes(x = point, y = true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Inverse Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("exp.inv.mr.png", plot = exp.inv.mr, height = 5, width = 6)

exp.mean.inv.mr <- ggplot()  + 
  geom_line(data = N_mean.xdf4, aes(x = point, y = med.value), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf4, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf4, aes(x = point, y = med.value), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4, aes(ymin = lower.hdi, ymax = upper.hdi, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf4, aes(x = point, y = true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Mean Inverse Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("exp.mean.inv.mr.png", plot = exp.mean.inv.mr, height = 5, width = 6)

exp.inv.mean.mr <- ggplot()  + 
  geom_line(data = N_mean.xdf5, aes(x = point, y = med.value, color = "Narrow"), lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf5, aes(ymin = lower.hdi, ymax = upper.hdi, x = point, fill = "Narrow"), alpha = 0.3)  + 
  geom_line(data = mean.xdf5, aes(x = point, y = med.value, color = "Wide"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf5, aes(ymin = lower.hdi, ymax = upper.hdi, x = point, fill = "Wide"), alpha = 0.2)  + 
  geom_line(data = mean.xdf5, aes(x = point, y = true_curve, color = "True Curve"), linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Inverse Mean Data)", 
       x = "Temperature", 
       y = "Mortality Rate", 
       fill = "95% HDI Bands", 
       color = "Posterior Curve")  + 
  scale_color_manual(values = c("Narrow" = cividis(10)[1], "Wide" = rocket(10)[5], "True Curve" = "black"))  + 
  scale_fill_manual(values = c("Narrow" = cividis(10)[1], "Wide" = rocket(10)[5]))  + 
  theme_minimal()
ggsave("exp.inv.mean.mr.png", plot = exp.inv.mean.mr, height = 5, width = 7)
```

```{r n.w.compare.exp.lt}
exp.ind.life <- ggplot()  + 
  geom_line(data = N_mean.xdf1, aes(x = point, y = med.value.inv), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf1, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf1, aes(x = point, y = med.value.inv), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf1, aes(x = point, y = true_curve.inv), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Individual Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("exp.ind.life.png", plot = exp.ind.life, height = 5, width = 6)

exp.mean.life <- ggplot()  + 
  geom_line(data = N_mean.xdf2, aes(x = point, y = med.value.inv), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf2, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf2, aes(x = point, y = med.value.inv), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf2, aes(x = point, y = 1/true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Mean Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("exp.mean.life.png", plot = exp.mean.life, height = 5, width = 6)

exp.inv.life <- ggplot()  + 
  geom_line(data = N_mean.xdf3, aes(x = point, y = med.value.inv), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf3, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf3, aes(x = point, y = med.value.inv), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf3, aes(x = point, y = true_curve.inv), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Inverse Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("exp.inv.life.png", plot = exp.inv.life, height = 5, width = 6)

exp.mean.inv.life <- ggplot()  + 
  geom_line(data = N_mean.xdf4, aes(x = point, y = med.value.inv), color = cividis(10)[1], lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf4, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = cividis(10)[1], alpha = 0.3)  + 
  geom_line(data = mean.xdf4, aes(x = point, y = med.value.inv), color = rocket(10)[5], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point), fill = rocket(10)[5], alpha = 0.2)  + 
  geom_line(data = mean.xdf4, aes(x = point, y = 1/true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Mean Inverse Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("exp.mean.inv.life.png", plot = exp.mean.inv.life, height = 5, width = 6)

exp.inv.mean.life <- ggplot()  + 
  geom_line(data = N_mean.xdf5, aes(x = point, y = med.value.inv, color = "Narrow"), lwd = 1)  + 
  geom_ribbon(data = N_mean.xdf5, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point, fill = "Narrow"), alpha = 0.3)  + 
  geom_line(data = mean.xdf5, aes(x = point, y = med.value.inv, color = "Wide"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf5, aes(ymin = lower.hdi.inv, ymax = upper.hdi.inv, x = point, fill = "Wide"), alpha = 0.2)  + 
  geom_line(data = mean.xdf5, aes(x = point, y = 1/true_curve, color = "True Curve"), linetype = "dashed")  + 
  labs(title = "Narrow and Wide Median Curve Comparison (Inverse Mean Data)", 
       x = "Temperature", 
       y = "Lifetime", 
       fill = "95% HDI Bands", 
       color = "Posterior Curve")  + 
  scale_color_manual(values = c("Narrow" = cividis(10)[1], "Wide" = rocket(10)[5], "True Curve" = "black"))  + 
  scale_fill_manual(values = c("Narrow" = cividis(10)[1], "Wide" = rocket(10)[5]))  + 
  theme_minimal()
ggsave("exp.inv.mean.life.png", plot = exp.inv.mean.life, height = 5, width = 7)

```

```{r n.w.compare.wb.lt}
wb.ind.life <- ggplot()  + 
  geom_line(data =  mean.xdf1_W_N, aes(x = point, y = med.value.inv), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf1_W, aes(x = point, y = med.value.inv), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf1_W, aes(y = log(2)/true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Individual WB Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("wb.ind.life.png", plot = wb.ind.life, height = 5, width = 6.5)

wb.mean.life <- ggplot()  + 
  geom_line(data =  mean.xdf2_W_N, aes(x = point, y = med.value.inv), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf2_W, aes(x = point, y = med.value.inv), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf2_W, aes(y = log(2)/true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Mean WB Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("wb.mean.life.png", plot = wb.mean.life, height = 5, width = 6.5)

wb.inv.life <- ggplot()  + 
  geom_line(data =  mean.xdf3_W_N, aes(x = point, y = med.value.inv), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf3_W, aes(x = point, y = med.value.inv), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf3_W, aes(y = 1/true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Inverse WB Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("wb.inv.life.png", plot = wb.inv.life, height = 5, width = 6.5)

wb.mean.inv.life <- ggplot()  + 
  geom_line(data =  mean.xdf4_W_N, aes(x = point, y = med.value.inv), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf4_W, aes(x = point, y = med.value.inv), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf4_W, aes(y = 1/true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Mean Inverse WB Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("wb.mean.inv.life.png", plot = wb.mean.inv.life, height = 5, width = 6.5)

wb.inv.mean.life <- ggplot()  + 
  geom_line(data =  mean.xdf5_W_N, aes(x = point, y = med.value.inv), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf5_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf5_W, aes(x = point, y = med.value.inv), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf5_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf5_W, aes(y = 1/true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Inverse Mean WB Data)", 
       x = "Temperature", 
       y = "Lifetime")  + 
  theme_minimal()
ggsave("wb.inv.mean.life.png", plot = wb.inv.mean.life, height = 5, width = 6.5)

wb.wb.ind.life <- ggplot()  + 
  geom_line(data =  mean.xdf6_W_N, aes(x = point, y = med.value.inv, color = "Narrow"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W_N, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv, fill = "Narrow"), alpha = 0.3)  + 
  geom_line(data =  mean.xdf6_W, aes(x = point, y = med.value.inv, color = "Wide"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv, fill = "Wide"), alpha = 0.3)  + 
  geom_line(data = mean.xdf6_W, aes(x = point, y = log(2)/true_curve, color = "True Curve"), linetype = "dashed")  + 
    labs(title = "Narrow and Wide Median Curve Comparison (Individual WB Data and WB Model)", 
       x = "Temperature", 
       y = "Lifetime", 
       fill = "95% HDI Bands", 
       color = "Posterior Curve")  + 
  scale_color_manual(values = c("Narrow" = mako(10)[8], "Wide" = plasma(10)[8], "True Curve" = "black"))  + 
  scale_fill_manual(values = c("Narrow" = mako(10)[8], "Wide" = plasma(10)[8]))  + 
  theme_minimal()
ggsave("wb.wb.ind.life.png", plot = wb.wb.ind.life, height = 5, width = 7.5)
```

```{r n.w.compare.wb.mr}
wb.ind.mr <- ggplot()  + 
  geom_line(data =  mean.xdf1_W_N, aes(x = point, y = med.value), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf1_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf1_W, aes(y = true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Individual WB Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.ind.mr.png", plot = wb.ind.mr, height = 5, width = 6.5)

wb.mean.mr <- ggplot()  + 
  geom_line(data =  mean.xdf2_W_N, aes(x = point, y = med.value), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf2_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf2_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf2_W, aes(y = true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Mean WB Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.mean.mr.png", plot = wb.mean.mr, height = 5, width = 6.5)

wb.inv.mr <- ggplot()  + 
  geom_line(data =  mean.xdf3_W_N, aes(x = point, y = med.value), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf3_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf3_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf3_W, aes(y = true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Inverse WB Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.inv.mr.png", plot = wb.inv.mr, height = 5, width = 6.5)

wb.mean.inv.mr <- ggplot()  + 
  geom_line(data =  mean.xdf4_W_N, aes(x = point, y = med.value), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf4_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf4_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf4_W, aes(y = true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Mean Inverse WB Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.mean.inv.mr.png", plot = wb.mean.inv.mr, height = 5, width = 6.5)

wb.inv.mean.mr <- ggplot()  + 
  geom_line(data =  mean.xdf5_W_N, aes(x = point, y = med.value), color = mako(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf5_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = mako(10)[8], alpha = 0.3)  + 
  geom_line(data =  mean.xdf5_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf5_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf5_W, aes(y = true_curve, x = point), color = "black", linetype = "dashed") + 
    labs(title = "Narrow and Wide Median Curve Comparison (Inverse Mean WB Data)", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.inv.mean.mr.png", plot = wb.inv.mean.mr, height = 5, width = 6.5)

wb.wb.ind.mr <- ggplot()  + 
  geom_line(data =  mean.xdf6_W_N, aes(x = point, y = med.value, color = "Narrow"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W_N, aes(x = point, ymin = lower.hdi, ymax = upper.hdi, fill = "Narrow"), alpha = 0.3)  + 
  geom_line(data =  mean.xdf6_W, aes(x = point, y = med.value, color = "Wide"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi, fill = "Wide"), alpha = 0.3)  + 
  geom_line(data = mean.xdf6_W, aes(x = point, y = true_curve, color = "True Curve"), linetype = "dashed")  + 
    labs(title = "Narrow and Wide Median Curve Comparison (Individual WB Data and WB Model)", 
       x = "Temperature", 
       y = "Mortality Rate", 
       fill = "95% HDI Bands", 
       color = "Posterior Curve")  + 
  scale_color_manual(values = c("Narrow" = mako(10)[8], "Wide" = plasma(10)[8], "True Curve" = "black"))  + 
  scale_fill_manual(values = c("Narrow" = mako(10)[8], "Wide" = plasma(10)[8]))  + 
  theme_minimal()
ggsave("wb.wb.ind.mr.png", plot = wb.wb.ind.mr, height = 5, width = 7.5)
```



```{r n.w.compare.rmse}
nar.wide.rmse.df <- rbind(boxplot.df, boxplot.df_N)
nar.wide.rmse.df$Set <- factor(c(rep("Wide", 1250), rep("Narrow", 1250)))
ggplot(nar.wide.rmse.df, aes(x = Temperature, y = RMSE, color = Set))  + 
  geom_line()  + 
  scale_color_manual(values = viridis(2))  + 
  facet_wrap(~ Method, scales = "free_y")  + 
  labs(title = "Line Plots for Each Method with Different Temperature Interval", 
       subtitle =  "Exponential Data", 
       x = "Temperature", 
       y = "RMSE") + 
  theme_classic()

nar.wide.rmse.df.wb <- rbind(boxplot.df.wb, boxplot.df.wb_N)
nar.wide.rmse.df.wb$Set <- factor(c(rep("Wide", 1500), rep("Narrow", 1500)))
ggplot(nar.wide.rmse.df.wb, aes(x = Temperature, y = RMSE, color = Set))  + 
  geom_line()  + 
  scale_color_manual(values = viridis(2))  + 
  facet_wrap(~ Method, scales = "free_y")  + 
  labs(title = "Line Plots for Each Method with Different Temperature Interval", 
       subtitle =  "Weibull Data", 
       x = "Temperature", 
       y = "RMSE") + 
  theme_classic()

barplot.df.exp <- rbind(RMSE.tab.exp, RMSE.tab.exp_N)
barplot.df.exp$Set <- factor(c(rep("Wide", 5), rep("Narrow", 5)))
barplot.df.exp |> ggplot(aes(x = Method, y = RMSE, fill = Set))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black")  + 
    geom_text(aes(label = round(RMSE, 4)), hjust = - 0.5, position = position_dodge(width = 0.9)) + 
  labs(x = "Method", y = "RMSE")  + 
  scale_fill_manual(values = viridis(2))  + 
  scale_x_discrete(limits = rev(levels(barplot.df.exp$Method))) + 
  coord_flip() + 
  labs(title = "RMSE Comparison Between Narrow and Wide Temperature Intervals", 
       subtitle = "Exponential Data") + 
  theme_classic()

barplot.df.wb <- rbind(RMSE.tab.wb, RMSE.tab.wb_N)
barplot.df.wb$Set <- factor(c(rep("Wide", 6), rep("Narrow", 6)))
barplot.df.wb |> ggplot(aes(x = Method, y = RMSE, fill = Set))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black")  + 
    geom_text(aes(label = round(RMSE, 4)), hjust = - 0.5, position = position_dodge(width = 0.9)) + 
  labs(x = "Method", y = "RMSE")  + 
  scale_fill_manual(values = viridis(2))  + 
  scale_x_discrete(limits = rev(levels(barplot.df.wb$Method))) + 
 # ylim(0, 0.1) + 
  coord_flip() + 
  labs(title = "RMSE Comparison Between Narrow and Wide Temperature Intervals", 
       subtitle = "Weibull Data") + 
  theme_classic()
```

```{r n.w.compare.data.rmse}
data.rmse.compare <- rbind(data.rmse.exp, N_data.rmse.exp)
data.rmse.compare$Set <- factor(c(rep("Wide", 5), rep("Narrow", 5)))
data.rmse.compare |> ggplot(aes(x = Method, y = RMSE, fill = Set))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black")  + 
    geom_text(aes(label = round(RMSE, 4)), hjust = - 0.5, position = position_dodge(width = 0.9)) + 
  labs(x = "Method", y = "RMSE")  + 
  scale_fill_manual(values = viridis(2))  + 
  scale_x_discrete(limits = rev(levels(data.rmse.compare$Method))) + 
  coord_flip() + 
  labs(title = "RMSE Comparison Between Narrow and Wide Temperature Intervals", 
       subtitle = "Exponential Data") + 
  theme_classic()

data.rmse.compare.wb <- rbind(data.rmse.wb, N_data.rmse.wb)
data.rmse.compare.wb$Set <- factor(c(rep("Wide", 6), rep("Narrow", 6)))
data.rmse.compare.wb |> ggplot(aes(x = Method, y = RMSE, fill = Set))  + 
  geom_bar(stat = "identity", position = "dodge", color = "black")  + 
    geom_text(aes(label = round(RMSE, 4)), hjust = - 0.5, position = position_dodge(width = 0.9)) + 
  labs(x = "Method", y = "RMSE")  + 
  scale_fill_manual(values = viridis(2))  + 
  scale_x_discrete(limits = rev(levels(data.rmse.compare.wb$Method))) + 
  ylim(0, 7) + 
  coord_flip() + 
  labs(title = "RMSE Comparison Between Narrow and Wide Temperature Intervals", 
       subtitle = "Weibull Data") + 
  theme_classic()
```

```{r weibull.data.compare}
wb.exp.plot.mr <- ggplot()  + 
  geom_line(data = mean.xdf1_W, aes(x = point, y = med.value), color = plasma(10)[8], lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[8], alpha = 0.3)  + 
  geom_line(data = mean.xdf6_W, aes(x = point, y = med.value), color = plasma(10)[2], lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W, aes(x = point, ymin = lower.hdi, ymax = upper.hdi), fill = plasma(10)[2], alpha = 0.3)  + 
  geom_line(data = mean.xdf1_W, aes(x = point, y = true_curve), color = "black", linetype = "dashed")  + 
  labs(title = "Median Curve with Interval Bands and True Curve", 
       x = "Temperature", 
       y = "Mortality Rate")  + 
  theme_minimal()
ggsave("wb.comp.mort.png", plot = wb.exp.plot.mr, width = 5, height = 5)

wb.exp.plot.life <- ggplot()  + 
  geom_line(data = mean.xdf1_W, aes(x = point, y = med.value.inv, color = "Exponential Model"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf1_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv, fill = "Exponential Model"), alpha = 0.3)  + 
  geom_line(data = mean.xdf6_W, aes(x = point, y = med.value.inv, color = "Weibull Model"), lwd = 1)  + 
  geom_ribbon(data = mean.xdf6_W, aes(x = point, ymin = lower.hdi.inv, ymax = upper.hdi.inv, fill = "Weibull Model"), alpha = 0.3)  + 
  geom_line(data = mean.xdf1_W, aes(x = point, y = log(2)/true_curve, color = "True Curve"), linetype = "dashed")  + 
  labs(title = "Median Curve with Interval Bands and True Curve", 
       x = "Temperature", 
       y = "Lifetime", 
       color = "Curve", 
       fill = "95% HDI Bands")  + 
  scale_color_manual(values = c("Exponential Model" = plasma(10)[8], "Weibull Model" = plasma(10)[2], "True Curve" = "black"))  + 
  scale_fill_manual(values = c("Exponential Model" = plasma(10)[8], "Weibull Model" = plasma(10)[2]))  + 
  theme_minimal()

ggsave("wb.comp.life.png", plot = wb.exp.plot.life, width = 6.5, height = 5)

```



```{r data.example.exp}
data.list[[100]]$inv.trait <- 1/data.list[[100]]$trait
group_means.plot <- tapply(data.list[[100]]$trait, data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.plot <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.plot)  # Extract means and unlist the result
    )
group_means.inv.plot <- tapply(data.list[[100]]$inv.trait, data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
df.mean.inv.plot <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(group_means.inv.plot)  # Extract means and unlist the result
    )


ind.plot <- ggplot(data.list[[100]], aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime", title = "Individual Data") + 
  theme_classic()
ggsave("ind.plot.png", plot = ind.plot, width = 3, height = 3)
mean.plot <- ggplot(df.mean.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime", title = "Mean Data") + 
  theme_classic()
ggsave("mean.plot.png", plot = mean.plot, width = 3, height = 3)
inv.plot <- ggplot(data.list[[100]], aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Inverse Data") + 
  theme_classic()
ggsave("inv.plot.png", plot = inv.plot, width = 3, height = 3)
mean.inv.plot <- ggplot(df.mean.plot, aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Mean Inverse Data") + 
  theme_classic()
ggsave("mean.inv.plot.png", plot = mean.inv.plot, width = 3, height = 3)
inv.mean.plot <- ggplot(df.mean.inv.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Inverse Mean Data") + 
  theme_classic()
ggsave("inv.mean.plot.png", plot = inv.mean.plot, width = 3, height = 3)

gridExtra::grid.arrange(ind.plot, mean.plot, inv.plot, mean.inv.plot, inv.mean.plot, nrow = 2)
```

```{r data.example.wb}
Weibull_data.list[[100]]$inv.trait <- 1/Weibull_data.list[[100]]$trait
wb.group_means.plot <- tapply(Weibull_data.list[[100]]$trait, Weibull_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
wb.df.mean.plot <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(wb.group_means.plot)  # Extract means and unlist the result
    )
wb.group_means.inv.plot <- tapply(Weibull_data.list[[100]]$inv.trait, Weibull_data.list[[100]]$T, function(x) {
    split_values <- split(x, rep(1:10, each = 10))
    means <- sapply(split_values, mean)
    return(means)
    })
wb.df.mean.inv.plot <- data.frame(
    T = c(rep(10, 10), rep(17, 10), rep(21, 10), rep(25, 10), rep(32, 10)), # Extract T values as numeric
    trait = unlist(wb.group_means.inv.plot)  # Extract means and unlist the result
    )


wb.ind.plot <- ggplot(Weibull_data.list[[100]], aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime", title = "Individual Data") + 
  theme_classic()
ggsave("wb.ind.plot.png", plot = wb.ind.plot, width = 3, height = 3)
wb.mean.plot <- ggplot(wb.df.mean.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "Lifetime", title = "Mean Data") + 
  theme_classic()
ggsave("wb.mean.plot.png", plot = wb.mean.plot, width = 3, height = 3)
wb.inv.plot <- ggplot(Weibull_data.list[[100]], aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Inverse Data") + 
  theme_classic()
ggsave("wb.inv.plot.png", plot = wb.inv.plot, width = 3, height = 3)
wb.mean.inv.plot <- ggplot(wb.df.mean.plot, aes(x = T, y = 1/trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Mean Inverse Data") + 
  theme_classic()
ggsave("wb.mean.inv.plot.png", plot = wb.mean.inv.plot, width = 3, height = 3)
wb.inv.mean.plot <- ggplot(wb.df.mean.inv.plot, aes(x = T, y = trait)) + 
  geom_point() + 
  labs(x = "Temperature", y = "1/Lifetime", title = "Inverse Mean Data") + 
  theme_classic()
ggsave("wb.inv.mean.plot.png", plot = wb.inv.mean.plot, width = 3, height = 3)

gridExtra::grid.arrange(wb.ind.plot, wb.mean.plot, wb.inv.plot, wb.mean.inv.plot, wb.inv.mean.plot, nrow = 2)
```

